### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by asherber** [mganss/ExcelMapper#10]
I needed to generate a largish Excel file for testing. I created 100K objects using [AutoBogus](https://github.com/nickdodd79/AutoBogus) and saved them to a file. With ExcelMapper, the Save operation took 15 minutes (!). The equivalent code with NPOI.Mapper took 10 seconds. Also, the file written by ExcelMapper was corrupt and gave me an error message:

![image](https://user-images.githubusercontent.com/5248041/52316359-f7ba8d00-2988-11e9-82c9-cf80af6b6140.png)

Here's the code I used; I can provide the Excel file if you want

```csharp
public void CreateFile()
{
    var people = AutoFaker.Generate<Order>(100000);
    var xl = new ExcelMapper();
    xl.Save(@"c:\myfile.xlsx", people);
}

public class Order
{
    public string Subcode { get; set; }
    public string CustomerName { get; set; }
    public uint Control_No { get; set; }
    public uint Web_Id { get; set; }
    public string Applicant { get; set; }
    public string SSN { get; set; }
    public uint COC_Number { get; set; }
    public DateTime Specimen_Date { get; set; }
    public string Lab { get; set; }
    public int ProductID { get; set; }
}
```

**Comment by mganss** [comment]
Thanks for reporting this. Fixed in 4.0.39.
