### ISSUE TITLE
Support C# 9 record types

### ISSUE THREAD

**Issue by drauch** [mganss/ExcelMapper#102]
It would be nice to use C# 9 record types as POCOs.

**Comment by mganss** [comment]
Records should already be supported. Is there something specific that doesn't work?

**Comment by mganss** [comment]
Got it. I guess I hadn't understood records 😳 Records are now supported, along with regular classes that don't have a default constructor.

**Comment by drauch** [comment]
That's great news. Nice!

One catch though: if one of the columns cannot be mapped (because no column header matches the parameter name) it should probably set this parameter to null instead of throwing a NullReferenceException.

StackTrace:
```
at Ganss.Excel.ExcelMapper.Fetch(ISheet sheet, Type type, Func`3 valueParser)+MoveNext()   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)   at UserQuery.AssertZero[T](IEnumerable`1 query), line 38   at UserQuery.Main(), line 6
```

:-)

**Comment by mganss** [comment]
Just pushed a new version that should fix this.

**Comment by drauch** [comment]
Nice, already tried it - works like a charm.

Big heart for you!

**Comment by mganss** [comment]
I've refactored the record related code a little, changing the constructor mapping convention: If there is no default constructor, the one with the highest number of parameters is used to initialize objects. Parameter names must equal their corresponding property names (ignoring case), the remaining parameters receive default values. Not currently supported are scenarios where there are additional properties that are not initialized through the constructor.
