### ISSUE TITLE
Exception 'Unable to convert "0,75" from *** to System.Decimal

### ISSUE THREAD

**Issue by DanielSanIT** [mganss/ExcelMapper#105]
I have a column that contains decimal and string values.
I am trying to add custom mapping by adding code below:
` excel.AddMapping<PriceAdjustments>("L55", p => p.L55).SetPropertyUsing(v => (v as string) == "NA" ? null : v);`
But the library cannot convert 0,75 to decimal using custom mapping. Double works fine, but I am not sure that double is good for financial information
Exception:
```
Ganss.Excel.Exceptions.ExcelMapperConvertException: 'Unable to convert "0,75" from [L:10]:[C:10] to System.Decimal.'
ArgumentException: Object of type 'System.Double' cannot be converted to type 'System.Nullable`1[System.Decimal]'.
```

Please note that the cell has a formula:
```
[Column(11)]
[FormulaResult]
public decimal? L55 { get; set; }
```

**Comment by mganss** [comment]
This should work:

```c#
excel.AddMapping<PriceAdjustments>("L55", p => p.L55)
    .SetPropertyUsing(v =>
{
    if ((v as string) == "NA") return null;
    return Convert.ChangeType(v, typeof(decimal));
});
```

**Comment by DanielSanIT** [comment]
Yep, works fine for me. Thank you!
