### ISSUE TITLE
Dotnet 5 support

### ISSUE THREAD

**Issue by ltemimi** [mganss/ExcelMapper#107]
Hi

I am unable to install the latest nuget package on a dotnet 5 console app
Is dotnet 5 supported?

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1108	Cycle detected. 
  ExcelMapper -> ExcelMapper (>= 5.1.270).	ExcelMapper	C:\Ref\Tests\ExcelMapper\ExcelMapper.csproj	1	

Yet My.ExcelMapper installs OK but does not work throws an exception it is not compatible

Thanks

**Comment by mganss** [comment]
.NET 5 is supported. Perhaps it's this: https://kmatyaszek.github.io/2019/05/30/nuget-nu1108-cycle-detected.html

**Comment by ltemimi** [comment]
Hi 
Thanks for the help it is now fixed.
just one small question can one read from a specific range in a specific sheet?

Regards
Laz

**Comment by mganss** [comment]
Yes, see here: https://github.com/mganss/ExcelMapper#header-row-and-data-row-range
