### ISSUE TITLE
Begin insertion at specified row when saving a sheet?

### ISSUE THREAD

**Issue by McPhale** [mganss/ExcelMapper#11]
Hello! Thanks again for the great product, I keep coming back to it.

Would it be possible to add a feature like "start inserting at row n" or "skip rows xyz" when saving a sheet? 

I've a template sheet I need to populate where the first row is supposed to be a banner of sorts.
![tosend](https://user-images.githubusercontent.com/7131919/53184061-02e4fe00-35c2-11e9-981a-9a25ae7e01d1.png)

**Comment by mganss** [comment]
Yes, that should be fairly easy. While we're at it, we could make it flexible so that you can specify the row number of the header row and a range of row numbers that contain the data.

I won't get to it within the next two weeks, though. If it's urgent, feel free to submit a PR.

**Comment by McPhale** [comment]
No rush! Sure, I may take a look at it if I have some extra time :)

**Comment by mganss** [comment]
In 5.0.41 there are now properties `HeaderRowNumber`, `MinRowNumber`, and `MaxRowNumber`.
