### ISSUE TITLE
Missing method  : 'Void NPOI.Util.LocaleUtil.SetUserTimeZone(System.TimeZone)'.

### ISSUE THREAD

**Issue by snow3461** [mganss/ExcelMapper#116]
Problem on first try to use this mapper.
Am I doing something wrong or is it a bug ?

```c#
public List<ProduitModel> GetAllProducts(string filePath)
        {
            var products = new ExcelMapper(filePath) { HeaderRow = false }.Fetch<ProduitModel>();
            return products.ToList<ProduitModel>();
        }
``` 

```c#
 public class ProduitModel
    {
        [Column(6)]
        public string InfoProduit { get; set; }
        [Column(9)]
        public string SousZoneRangement { get; set; }
        [Column(10)]
        public string UniteStock { get; set; }
        [Column(5)]
        public string CodeArticle { get; set; }
        [Column(2)]
        public string Designation { get; set; }
        [Column(3)]
        public string FluxAppro { get; set; }
        [Column(4)]
        public string  ListeInventaire { get; set; }

    }
```
Results in : System.MissingMethodException: 'Missing method : 'Void NPOI.Util.LocaleUtil.SetUserTimeZone(System.TimeZone)'.'

[sample.xlsx](https://github.com/mganss/ExcelMapper/files/6191425/sample.xlsx)

**Comment by mganss** [comment]
Are you using NPOI 2.5.2?
This is currently not supported because of https://github.com/nissl-lab/npoi/issues/473
You need to downgrade to 2.5.1.

**Comment by snow3461** [comment]
Thanks, that was a good hint.

Another test project in my solution was referencing NPOI 2.5.2, and I somehow had a binding redirect to this version (I was not very familiar with this until now).
Its working as expected now.

Thanks again.

**Comment by mganss** [comment]
You can now use NPOI 2.5.3 from 5.1.294.
