### ISSUE TITLE
No append to Excel file methods

### ISSUE THREAD

**Issue by RebelionTheGrey** [mganss/ExcelMapper#12]
Hello.

Is it possible to realize feature like an append data to the end of the current opened file?
The situation: I have some block of identically structured data. I want to write these blocks each below other (with, possibly, same delimiters). Current realization of the Save method rewrite current saved file:

```
var saveFile = new ExcelMapper() { HeaderRow = true, };
saveFile.Save<OutputDTO>("outputFile.xlsx", object1);
saveFile.Save<OutputDTO>("outputFile.xlsx", object2);
```
Thank you! It's a really great package! I spent a lot of time, thinking about realization of my own, but your package covers all of my problems I need to solve. Pls, do not abandon it!

**Comment by mganss** [comment]
Thanks for the kind words. I won't abandon the project, but I consider it more or less "done", except for bug fixes or minor features.

I'm not sure I understand your use case properly. Can't you collect all the objects you want to save and then write them out in one go? So for example:

```c#
saveFile.Save<OutputDTO>("outputFile.xlsx", object1.Concat(object2));
```

**Comment by RebelionTheGrey** [comment]
Hello, mganss!

Thank you for your answer.
I meant this:
Let me have 3 containers with data ordered in the same table. I want to write each table one below other with an additional information (for example, some statistics for tabled data) and separator (for example, 2-3 empty lines).

saveFile.Save<OutputDTO>("outputFile.xlsx", object1.Concat(object2)) won't give me the same functionality. Possibly, It could be realized through adding another .Save method, which get rowNumber as a parameter. This parameter describes the row from which the .Save method should start to write data.

**Comment by mganss** [comment]
I haven't tested this, but I believe this scenario should be possible with the recently introduced `MinRowNumber` and `MaxRowNumber` properties (see #11). Before saving each block of objects, set these properties to the appropriate range of rows in your Excel table.

**Comment by RebelionTheGrey** [comment]
Oh, great, thank you!! I'll test it soon!!

**Comment by RebelionTheGrey** [comment]
That works awesome, thnak you!
Offtop question - will you make the .NET Core version of your library? Thank you!

**Comment by mganss** [comment]
Great! It already supports netstandard2.0, so you can use it from a .NET Core application.

**Comment by RebelionTheGrey** [comment]
Thank you! Think, the issue could be closed!
