### ISSUE TITLE
Random access to worksheet cells?

### ISSUE THREAD

**Issue by Luke-Robinett** [mganss/ExcelMapper#123]
In addition to mapping class properties to columns, is it possible to address a specific cell location in a worksheet? I need to parse Excel sheets where A1 is the label for the value in A2, B1 is the label for the value in B2 and the actual column headings begin on C1. For example, A1 = "Entity Type", A2 = "Discount Code", B1 = "Export Time" and B2 = "5/13/2021 5:00:00 PM." I'd like to do something like: myObject.ExportTime = excel["B2"] but can't find anything like that in the documentation. Hope this made sense, and thank you for your help! This library is really great.

**Comment by mganss** [comment]
If I understand correctly there are only 2 rows for columns A and B which contain metadata and the "real" data which you map to objects starts from column C. So there are 2 classes, one for the metadata and the other for the real data right?

You can perform two mapping passes, restricting the number of rows when reading the metadata by setting `MaxRowNumber` to 1. If you can't or don't want to map to static objects you can map to dynamic objects and access the properties by the corresponding column letter:

```c#
var meta = new ExcelMapper(...) { HeaderRow = false, MaxRowNumber = 1 }.Fetch().First();
var entityType = meta.A;
var exportTime = meta.B;
```

**Comment by mganss** [comment]
Feel free to reopen if this is still an issue.
