### ISSUE TITLE
Saving multiple sheets to a stream doesn't save all sheets

### ISSUE THREAD

**Issue by Venu-prahalad** [mganss/ExcelMapper#127]
Hi,
I am reading a file to a memory stream, passing the memory stream to excel mapper, fetching sheets, performing business logic and trying to save all the sheets to a new output stream. At this point Excel saved is corrupt and only one of the sheet is saved.
Below is the code snippet

           `//Read from file
            MemoryStream memoryStream = new MemoryStream();
            memoryStream.Write(System.IO.File.ReadAllBytes("c:/temp/Book1.xlsx"));

            var excelMapper = new ExcelMapper(memoryStream);
            var sh1 = excelMapper.Fetch<Sheet1>(1);
            var sh2 = excelMapper.Fetch<Sheet2>(0);
            var sh3 = excelMapper.Fetch<Sheet3>(3);
            var sh4 = excelMapper.Fetch<Sheet4>(2);

            //Build data for sheet3 and sheet 4
            var sheet3 = new List<Sheet3>() { new Sheet3() { Sheet3Col1 = "3113", Sheet3Col2 = "3123" },
            new Sheet3() { Sheet3Col1 = "3213"+DateTime.Now.ToString(), Sheet3Col2 = "3223" }};
            var sheet4 = new List<Sheet4>() { new Sheet4() { Sheet3Col1 = "3113", Sheet3Col2 = "3123" },
            new Sheet4() { Sheet3Col1 = "3213", Sheet3Col2 = "3223" }};

            //Write sheet3 and sheet4 to memory stream
            MemoryStream memoryStreamOp = new MemoryStream();
            excelMapper.Save<Sheet3>(memoryStreamOp, sheet3, "Sheet3", true);
            excelMapper.Save<Sheet4>(memoryStreamOp, sheet4, "Sheet4", true);

           //write to file
            var fsStreamOp = System.IO.File.OpenWrite("c:/temp/Book1Op1.xlsx");
            fsStreamOp.Write(memoryStreamOp.ToArray());
            fsStreamOp.Close();`

If the above code is run then sheet1,sheet2 and sheet3 have data however sheet4 doesn't have. Also when the excel file is open it prompts that the file is corrupt.
Is there something I am doing wrong or is this a bug?
Your help in this regard is greatly appreciated.

**Comment by mganss** [comment]
You're writing two copies of the Excel file to the same `MemoryStream`, that's why the file appears as corrupt.

You need to write to a fresh stream on the last call to `Save()`. So if you want to save multiple sheets you can pass the same `MemoryStream` as in your example on all calls to `Save()` except the last one. The `MemoryStream` will be a dummy in this case as you're only interested in the side effect of `Save()` saving the objects in the internal workbook of the `ExcelMapper` object.
With the last call you can then save the complete workbook to your output file. For example:

```c#
var ms = new MemoryStream(); // dummy
excelMapper.Save(ms, sheet1, "Sheet1");
excelMapper.Save(ms, sheet2, "Sheet2");
excelMapper.Save(ms, sheet3, "Sheet3");
excelMapper.Save("MultipleSheets.xlsx", sheet4, "Sheet4");
```

**Comment by Venu-prahalad** [comment]
@mganss Thank you for your reply.
The reason I choose to write it to stream is that the xlsx file being created would go to azure blob storage. Hence I don't think `excelMapper.Save("MultipleSheets.xlsx", sheet4, "Sheet4");` is an option for me. I was thinking to write to a stream and finally write the stream to an azure blob. Any suggestion you have to write multiple sheets to stream so I can save it to blob directly?

**Comment by mganss** [comment]
Sure, you can write to any stream, just make sure you pass a  fresh stream on the last call as `Save()` writes a full Excel file on each call:

```c#
var ms = new MemoryStream(); // dummy
excelMapper.Save(ms, sheet1, "Sheet1");
excelMapper.Save(ms, sheet2, "Sheet2");
excelMapper.Save(ms, sheet3, "Sheet3");
var realStream = new MemoryStream(); // or whatever stream you want to write to
excelMapper.Save(realStream, sheet4, "Sheet4");
```

**Comment by Arturace** [comment]
Thanks @mganss for the explanation! For people stumbling onto this in the future, consider using `Stream.Null` instead of a real active stream to avoid unecessary writes.

```
excelMapper.Save(Stream.Null, sheet1, "Sheet1");
excelMapper.Save(Stream.Null, sheet2, "Sheet2");
excelMapper.Save(Stream.Null, sheet3, "Sheet3");
var realStream = new MemoryStream();
excelMapper.Save(realStream, sheet4, "Sheet4");
```
