### ISSUE TITLE
Open Excel file as "read-only"

### ISSUE THREAD

**Issue by mgmiles** [mganss/ExcelMapper#128]
If I have the Excel file open in Excel, I get the error " System.IO.IOException: 'The process cannot access the file 'c:\utils\licences\bulkpurchase.xlsm' because it is being used by another process.' 

Is there an option to allow ExcelMapper to open the file in read-only mode?

The old Linq2Excel code did have a "ReadOnly" option.

**Comment by mganss** [comment]
You can use an overload of the constructor, `Fetch()`, or `FetchAsync()` that takes a `Stream` and pass a `FileStream` that has been opened with `FileShare.ReadWrite`:

```c#
using var fs = File.Open(file, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
var excel = new ExcelMapper(fs);
// ...
```

**Comment by mgmiles** [comment]
Perfect, thanks for the quick response.
