### ISSUE TITLE
Remove "Sealed" specification for ColumnAttribute class 

### ISSUE THREAD

**Issue by RebelionTheGrey** [mganss/ExcelMapper#13]
Hello again!

Nowadays I write ASP.NET Core backend. So, I want to use your library as a servic, but if I want to use annotaions for columns, I should strongly add a reference to the ExcelMapper library in the main application, not only in my service realization. And I cannot "wrap" Column attribute by my own specifications derived from ColumnAttribute because ColumnAttribute class is marked as "sealed". 
Is it possible to "unseal" it? Or maybe you know another elegant solution for this problem? 

Thank you!

**Comment by mganss** [comment]
I don't understand the use case yet. Can you provide a code example?

**Comment by RebelionTheGrey** [comment]
Hello, mganss!

So, for example, I have one project in which I want to realize report service. I create interface, for example, `IReportService` with some abstract methods for report creation. Okay, go next. I get 2 services (for excel generation and for pdf generation), each service use Column attribute for mapping properties. And I want to use DI to inject the service I currently need in my app. So, In the current realization with sealed ColumnAttribute class I have 2 ways: add ExcelMapper dependency into my report service explicitly or not to use ColumnAttributes and realize internal mapping through the existing functionality.
So, could you "unseal" ColumnAttribute in your next release or it's not possible? 

Thank you.

**Comment by mganss** [comment]
I'm sorry, I still don't understand. A short code example would help me a lot. Can't you use separate attributes for your additional functionality?

**Comment by RebelionTheGrey** [comment]
Hm...

Let's try.

There are interfaces.
```
    interface IReportGeneration
    {
        T Generate<U, T>(IEnumerable<U> objects, JObject jsonSchema = null) where T : Stream, new() where U : class;
    }
    interface IFileParsing
    {
        void Open(string filename);
        void Open(Stream stream);

        IEnumerable<T> Parse<T>(JObject schema = null) where T : class, new();
    }
```

This is my realization of ExcelWorkloadService.
```
    public class ExcelWorkloadService : IFileParsing, IReportGeneration
    {
        protected ExcelMapper excelObject;

        public ExcelWorkloadService() { }

        public T Generate<U, T>(IEnumerable<U> objects, JObject schema = null) where T : Stream, new() where U: class
        {
            var stream = new T();

            excelObject.Save<U>(stream, objects);

            return stream;
        }

        public void Open(string filename) => excelObject = new ExcelMapper(filename) { HeaderRow = true, };
        public void Open(Stream stream) => excelObject = new ExcelMapper(stream) { HeaderRow = true, };
        public IEnumerable<T> Parse<T>(JObject schema = null) where T : class, new() => excelObject.Fetch<T>();
    }
```

This is the part of my ASP.NET Core Web API (which doen't know anything about ExcelMapper, you see).

```
services.AddScoped<IFileParsing, ExcelWorkloadService>();
services.AddScoped<IReportGeneration, ExcelWorkloadService>();
```

Suppose, we need to write same class - MyTestExcelClass by Generate method from IReportGeneration.

```
public class MyTestExcelClass
{
    [Column("MyField1")]
    public int Field1 { get; set; }
    [Column("MyField2")]
    public int Field2 { get; set; }
    [Column("MyField3")]
    public int Field3 { get; set; }
}
...
var  writeObjectsList=  new List<MyTestExcelClass>(); {we suppose that somewhere in the code this list is filled)
...

IReportGeneration report; (we suppose here that report  is filled by ASP.NET Core DI mechanism in the same Controller constructor).

var result = report.Generate<MemoryStream, MyTestExcelClass>(writeObjectsList);
```

As you could see, this realization strongly needs to install dependency to ExcelMapper in main ASP.NET Core app through Nuget and using directive. Also, If I want to use PDFReportGenerator, I must change dependency.

But If I'll have an ability to derive my Attribute class from ColumnAttribute, It wouldn't need to install package in the main project, I could use the same variant of my code:

```
public class MyTestExcelClass
{
    [DerivedColumn("MyField1")]
    public int Field1 { get; set; }
    [DerivedColumn("MyField2")]
    public int Field2 { get; set; }
    [DerivedColumn("MyField3")]
    public int Field3 { get; set; }
}

where 
DerivedColumnAttribute: ColumnAttribute
{
}
```

By the Liskov principle it should work properly. Is it correct?

**Comment by mganss** [comment]
While on surface it might look like you wouldn't need a dependency on ExcelMapper, you still would because the package that contains `DerivedColumnAttribute` would need to depend on ExcelMapper. In other words, all packages in the dependency graph are installed when you install a package.

You can see this in Visual Studio when you expand the "Dependencies" tree within a project. For example, ExcelMapper depends on NPOI which in turn depends on SharpZipLib etc.

**Comment by RebelionTheGrey** [comment]
mganss, yes, but It's a hidden dependencies - I don't need to install NPOI in my project explicitly. For example, If I need to use ExcelReportGenerator, I must include in my project not only "using ExcelReportGenerator", but also "using Ganss.Excel". That's an explicit dependency for me.

**Comment by mganss** [comment]
I don't see the benefit of "hiding" the dependency. Also, it's a .NET best practice to seal custom attributes: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1813-avoid-unsealed-attributes
https://rules.sonarsource.com/csharp/tag/performance/RSPEC-4060
Json.NET does it, too: https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonConverterAttribute.htm

**Comment by RebelionTheGrey** [comment]
Yeah, I see. I think, I should find another method for me... I don't understand the reason for attribute classes sealing, but if this is compliant code paradigm, let it be...
