### ISSUE TITLE
Yet another question about custom mapping

### ISSUE THREAD

**Issue by geon-ru-eaa** [mganss/ExcelMapper#130]
How can i map string[] (property) to csv (one cell, delimeter - ';') and vice versa?

**Comment by mganss** [comment]
Nested object processing interfered with custom mapping. I have added a fix for this scenario. Here's how you can specify the custom mapping: https://github.com/mganss/ExcelMapper/blob/e8fc469715fba797e273a8504932622cbae99c22/ExcelMapper.Tests/Tests.cs#L2318-L2338

**Comment by mainefremov** [comment]
```c#
public class MyType
{
    public bool[] CategoryIsActive { get; set; }
}
```
```c#
excel.AddMapping<MyType>("MyHeaderName", p => p.CategoryIsActive)
    .SetCellUsing((c, o) =>
    {
        if (o is bool[] b) c.SetCellValue(string.Join(";", b.Select(x => x ? "Y" : "N")));
        else c.SetCellValue((string)null);
    })
    .SetPropertyUsing(v =>
    {
        if(v is string s) return s.Split(';').Select(x => (x == "Y")).ToArray();
        else return Array.Empty<bool>();
    });
```
Not works (
In debugger, after first and correct assignment goes second assignment with empty boolean array.

**Comment by mganss** [comment]
Please attach a demo Excel file.

**Comment by geon-ru-eaa** [comment]
> Please attach a demo Excel file.

Solved:
```c#
excel.Ignore<MyType>(p => p.CategoryIsActive);
excel.AddMapping<MyType>("MyHeaderName", p => p.CategoryIsActive){
```

**Comment by mganss** [comment]
Should now work without `Ignore`.
