### ISSUE TITLE
Read file with only a header row

### ISSUE THREAD

**Issue by Gordon68** [mganss/ExcelMapper#136]
I would like to be able to read an excel file with only a header row. Currently this throws an exception. These files are either templates or exported empty data.

It would be really handy if there was a way to read an empty file, as long as the columns matched the POCO. Even a specific EmptyFileException would be helpful

**Comment by mganss** [comment]
I can't repro. Can you attach an example Excel file here?

**Comment by Gordon68** [comment]
Example file
[Users.xlsx](https://github.com/mganss/ExcelMapper/files/6938661/Users.xlsx)

**Comment by mganss** [comment]
Thanks. Still can't repro, though. What does your class definition look like?

**Comment by Gordon68** [comment]
using Ganss.Excel;

namespace Blah.Models
{
    public class UserExport
    {
        [Column(1)]
        public string Name { get; set; }
        [Column(2)]
        public string Username { get; set; }
        [Column(3)]
        public string UserType { get; set; }
        [Column(4)]
        public string Email { get; set; }
        [Column(5)]
        public string Active { get; set; }
        [Column(6)]
        public string LastLogin { get; set; }
        [Column(7)]
        public string PasswordExpires { get; set; }
        [Column(8)]
        public string LockedOut { get; set; }
        [Column(9)]
        public string DateLockedOut { get; set; }
        [Column(10)]
        public string RolePackages { get; set; }

        public UserExport()
        {

        }
    }
}

**Comment by mganss** [comment]
Strange, still can't repro 🤷🏻  I'm just doing this:

```c#
var excelMapper = new ExcelMapper("Users.xlsx");
var users = excelMapper.Fetch<UserExport>().ToList();
```

What does your code look like and what kind of exception (including stack trace) do you get?

**Comment by Gordon68** [comment]
var data = new ExcelMapper(filename).Fetch<UserExport>();

ArgumentOutOfRangeException Message = "Specified argument was out of the range of valid values. (Parameter 'index')"

**Comment by mganss** [comment]
Note that this fetches dynamic objects, not objects of the static class you have defined. But I still can't repro. Can you post the stack trace? Also, which platform are you on (.NET Framework or .NET Core, Windows/Linux/macOS)?

**Comment by Gordon68** [comment]
so this is kinda wrong?

public static UserExport GetUserExportData()
        {
            var filename = GetDownloadFolder() + ExportFileName.User;
            var data = new ExcelMapper(filename).Fetch<UserExport>();

            return new UserExport
            {
                Name = data.ElementAt(0).Name,
                Username = data.ElementAt(0).Username,
                UserType = data.ElementAt(0).UserType,
                Email = data.ElementAt(0).Email,
                Active = data.ElementAt(0).Active,
                LockedOut = data.ElementAt(0).LockedOut,
                RolePackages = data.ElementAt(0).RolePackages.Trim()
            };
        }

**Comment by Gordon68** [comment]
.NET 5

**Comment by mganss** [comment]
I guess the exception occurs at the calls to `ElementAt(0)` if the enumerable contains no elements.
This should work:

```c#
var data = new ExcelMapper(filename).Fetch<UserExport>().FirstOrDefault();
return data;
```

This will return `null` if there are no records. If you must keep the call to `Trim()` then you need to check `data` for null and then call `Trim()`:

```c#
if (data != null) { data.RolePackages = data.RolePackages.Trim(); }
```

Is it intended that only the first user is returned?

**Comment by Gordon68** [comment]
Yes thanks
I dunno what I was thinking (I stepped through the code again)

Thank you for your help and thank you for ExcelMapper
