### ISSUE TITLE
Apply styles to cells?

### ISSUE THREAD

**Issue by LukeAvea** [mganss/ExcelMapper#144]
When doing a custom mapping function, is it possible to also apply a custom style? For example, if a property meets certain criteria, format it as a hyperlink, make it blue, underline it etc. when it is written to the sheet

**Comment by mganss** [comment]
Yes, it's possible. This sets the background to red where the `Name` property contains `"l"`:

```c#
var excelMapper = new ExcelMapper();
var columnInfo = excelMapper.AddMapping<ProductPosRecord>("Name", p => p.Name);
var setter = columnInfo.SetCell;

columnInfo.SetCellUsing((ICell c, string s) =>
{
    setter(c, s);
    if (s.Contains("l"))
    {
        CellUtil.SetCellStyleProperty(c, CellUtil.FILL_FOREGROUND_COLOR, IndexedColors.Red.Index);
        CellUtil.SetCellStyleProperty(c, CellUtil.FILL_PATTERN, FillPattern.SolidForeground);
    }
});

excelMapper.Save("products.xlsx", products);
```

**Comment by LukeAvea** [comment]
This is great! Thank you. I’d stumbled upon a similar approach since originally submitting this issue but yours is far cleaner.
