### ISSUE TITLE
Writing a custom Heading before Content

### ISSUE THREAD

**Issue by ChristianKern97** [mganss/ExcelMapper#145]
Hey there, i did not find anything on this issue yet so here we are.

I try to fill a custom template with content, but in the first row there are two headings, that need to be adjusted with custom text. Is there a way to just change the text of a certain cell for this?

Example of what i want to do: (i want to change the red stuff)
![grafik](https://user-images.githubusercontent.com/28393606/133151534-e7d6fc6e-8f60-437b-967a-cd7a011709a8.png)

**Comment by mganss** [comment]
I think this should be possible. There is no builtin method to do it but you can use NPOI to manipulate the `Workbook` object that you pass to ExcelMapper. So, first create a `Workbook` object:

```c#
var wb = WorkbookFactory.Create(file);
```

Use this object to manipulate the cell values of the first row, then pass it to ExcelMapper's constructor, making sure you specify `HeaderRowNumber = 1` to indicate that the real header row is the second row.

**Comment by ChristianKern97** [comment]
Yeah of course. I don't know why i didn't think about that
