### ISSUE TITLE
Microsoft.Office.Interop.Excel.Application has no suitable constructor

### ISSUE THREAD

**Issue by vefaokumus** [mganss/ExcelMapper#146]
Hi. I suddenly started to get this error:

_Ganss.Excel.Exceptions.ExcelMapperConvertException: 'Type Microsoft.Office.Interop.Excel.Application has no suitable constructor._

Yesterday it was working like charm but suddenly started to give this error. I am pretty sure I didn't change anything. The file I try to fetch is attached. Thanks.

[batch_analyses-a02.xlsx](https://github.com/mganss/ExcelMapper/files/7165081/batch_analyses-a02.xlsx)

**Comment by mganss** [comment]
Which of the sheets does the error occur at? Please also show the class definition.

**Comment by vefaokumus** [comment]
Sorry for not enough info. It is the "Analyses" sheet. Here is my class definition:

`
        public int ID { get; set; }
        public string[] FileArrayAnalysis { get; set; }
        public string[] FileArrayDefinitions { get; set; }
        public string Motion { get; set; }
        public double TotalTime { get; set; }
        public int NumberOfIncrement { get; set; }
        public string Recorder { get; set; }
        public int MotionNumber { get; set; }
`

And there are some methods in my class definition.

**Comment by mganss** [comment]
I can't repro. Does the class have a default constructor?

**Comment by vefaokumus** [comment]
Yes I tried to add a default constructor. I think something wrong with my system. Because there wasn't any problem two days ago. Thanks for the help. Should I close the issue?

**Comment by mganss** [comment]
Are you sure there aren't any other properties on the class? If so, add the `[Ignore]` attribute to those.

I'll close the issue. Feel free to reopen if the issue persists.
