### ISSUE TITLE
Is there a way of getting a line number (mapped to a property?)

### ISSUE THREAD

**Issue by navin-hn** [mganss/ExcelMapper#148]
In a mapping requirement I have, we wanted to get the line number recorded for each row read. Unfortunately line number is not a column in spreadsheet and cannot be added (template restrictions). Is there a way of just getting line number when mapping into a new property?

I can think of returning the mapped result into a list and then running a linq statement like:

int rowLineNumber = 3;
lstFileItems.ForEach(fi => fi.LineNumber = rowLineNumber++);

but was wondering if there is a better way whilst parsing the file instead?

**Comment by mganss** [comment]
Yes, you can use `SetPropertyUsing`. Manually map any of the regular columns and set the row number property in the mapping function. You can combine mapping through attributes with manual mapping so you don't have to manually map the other columns.

```c#
var excel = new ExcelMapper("products.xlsx");
excel.AddMapping<Product>("Name", p => p.Name)
    .SetPropertyUsing<Product>((p, v, c) =>
    {
        p.Row = c.RowIndex;
        return v;
    });
var products = excel.Fetch<Product>().ToList();
```

**Comment by navin-hn** [comment]
works a treat. thanks
