### ISSUE TITLE
AddMapping on Multiple Columns?

### ISSUE THREAD

**Issue by McPhale** [mganss/ExcelMapper#15]
This is probably a long shot, but how hard would it be to implement a feature where you could apply a single custom mapping rule to multiple columns in one go?  For instance, I've got a sheet from another department I need to work with that has a bunch of columns (like 10) that should map to boolean properties, but the sheet itself has strings "Y" or "N" in the columns.

I could use .AddMapping on all of the requisite properties, but then I'm repeating essentially the same code a bunch of times; maybe you have some suggestions on how to handle that? 

If it makes sense to add some sort of feature like that to ExcelMapper I'd be happy to take a look at it if you have any thoughts on where to start.

**Comment by mganss** [comment]
You can iterate over the `ColumnInfo` objects that are returned by `AddMapping()` and call `SetCellUsing()` and `SetPropertyUsing()` on all of them without duplicating code:

```c#
foreach (var ci in new[] { "Name", "Price", "Value" }.Select(p => e.AddMapping(typeof(Product), p, p)))
{
    ci.SetCellUsing((c, o) => { c.SetCellValue((o as bool?) == true ? "yes" : "no"); });
    ci.SetPropertyUsing(v => (v as string) == "yes");
}
```

The call to `AddMapping()` might be redundant if you only need to get the `ColumnInfo` objects. In that case, you can also call `GetColumnByName()` or `GetColumnByIndex()` on the `TypeMapper` object to get the `ColumnInfo` objects for columns that are mapped by convention or attributes.

**Comment by McPhale** [comment]
That seems to have worked; thank you!
