### ISSUE TITLE
How to autoset column width?

### ISSUE THREAD

**Issue by dutbu2718** [mganss/ExcelMapper#153]
Hi, when I map POCO with the column annotations to a memory stream (will send this stream as an HTTP response) and save it as a file the header row columns are squashed together and won't automatically expand. 

How can I tell Excelmapper to expand the header row column width when mapping the POCOs?

    public async Task<bool> GenerateExcelAsync(MemoryStream writeStream, IEnumerable<SampleModel> samples)
    {
        var successFlag = true;
    
        try
        {
            var results = MapToSampleInformationViewModels(samples);
    
            // create an empty object so ExcelMapper will create a header row for the excel
            if (!results.Any())
            {
                results = new List<SampleInformationViewModel>
                {
                    new SampleInformationViewModel()
                };
            }
    
            var excel = new ExcelMapper();
            await excel.SaveAsync(writeStream, results);
        }
        catch (Exception e) when (e is ArgumentNullException or InvalidOperationException)
        {
            successFlag = false;
        }

        return successFlag;
    }

**Comment by mganss** [comment]
This would have to be done by manipulating the workbook thorough NPOI. 

If this can be achieved by just setting an auto expand flag then your best bet is probably to pass an existing workbook object to ExcelMapper. 

OTOH, if the widths of the headers need to be adapted to the content widths manually before saving, then I'll have to add an event that gets invoked just prior to writing to the stream.

**Comment by dutbu2718** [comment]
Hi, the widths of the headers need to be adapted to the content widths manually before saving to a memory stream.

**Comment by mganss** [comment]
OK, I won't be able to add the event until next week, though. 

As a temporary workaround, you might want to save to a MemoryStream, then read back into an NPOI workbook again, manipulate the headers, and save back out again.

**Comment by dutbu2718** [comment]
Hi, thanks I will try your suggestion (I just need to read about NPOI).

**Comment by mganss** [comment]
I've added the event. This should work for autosizing the columns:

```c#
excelMapper.Saving += (s, e) =>
{
    var cols = e.Sheet.GetRow(excelMapper.HeaderRowNumber).LastCellNum;

    for (int i = 0; i < cols; i++)
        e.Sheet.AutoSizeColumn(i);
};
```

**Comment by MrChriZ** [comment]
So I've ran into a slight problem with this feature.  As far as I can see this only works if the the data row width is less wide than the header width.

Counter to how you would expect it to work Excel does not autowidth the whole column - just for the width of the particular row you have selected.  Hence in Excel you must select all the rows you wish to autowidth for.

Could the feature be expanded to also take a row?

**Comment by MrChriZ** [comment]
Ah this looks like an issue in NPOI rather than ExcelMapper...

**Comment by MrChriZ** [comment]
OK downgrading to version 5.2.429 of ExcelMapper which in turn uses the previous version of NPOI seems to resolve the issue for me.
