### ISSUE TITLE
Columns from POCO base classes, but not data

### ISSUE THREAD

**Issue by kbrung** [mganss/ExcelMapper#158]
If the type you're trying to save to Excel format is inheriting from a base class, you get the columns but not the data. Looking at the code, it seems to be the intention not to extract data based on the property not having the declaring type the same as the mapper type.

Example:

``` C#
public class IdBase
{
  public int Id;
}

public class Movie: IdBase
{
  public string Name;
}
```

However, you still get the columns, albeit empty ones. In the example, you get an Id column with no data.

If I may make a request, I would like to be able to save the inherited fields also.

**Comment by mganss** [comment]
Sorry for the late response. I won't be able to investigate until the 29th as I'm not near a computer until then.

**Comment by mganss** [comment]
I can't repro. Please post an example Excel file and the code you're using to fetch objects from the file.

**Comment by MrTanXin** [comment]
I have the same problem

Example:

```
    public class Base
    {
        [Column("Id")]
        public int Index { get; set; }
    }

    public class Name:Base
    {
        [Column("Name")]
        public int Name{ get; set; }
    }
```

Export Excel like this:
| Name | Id |
| -- | -- |
| Tom  | |
| John | |

Id is Empty and Name have value

I Use ExcelMapper Version is 5.2.337 with .NET 5 Project 

I hope to fix ASAP 
Thinks a lot 
Have a nice Day :)

**Comment by kbrung** [comment]
The reason for this is line 1000 in ExcelMapper.cs.

**Comment by MrTanXin** [comment]
ExcelMapper is very Useful in my work
I hope this project is more better 

Thank you to reply my issue

**Comment by mganss** [comment]
OK got it and fixed.
