### ISSUE TITLE
Option to ignore subtypes

### ISSUE THREAD

**Issue by kbrung** [mganss/ExcelMapper#159]
I would like to request a feature of setting a flag to ignore any sub-types.

**Comment by mganss** [comment]
How do you envision this to be surfaced?

**Comment by kbrung** [comment]
`ExcelMapper mapper m = new();
m.IgnoreSubTypes = true;`

Or something more modern. Either way, just a simple flag.

In the code I imagine checking the flag before any of these lines:

`foreach (var col in columnsByName.SelectMany(c => c.Value.Where(c => c.Directions.HasFlag(MappingDirections.ObjectToExcel) && c.IsSubType)))`

A simple flag to turn off the advanced feature of saving sub type rows.
