### ISSUE TITLE
Fetch method removes columns with newlines in the header row

### ISSUE THREAD

**Issue by McPhale** [mganss/ExcelMapper#16]
Not really sure if it should be considered a bug or just a limitation, but if you've got a header row with newlines in the text of the cell, the fetch method throws that column out of the column list. (Why anyone would set a sheet up that way, I don't know; I just work with what they give me.) 

It's easily remedied by "ignoring" the header row and mapping via indices, so it's not a pressing issue either way, but it was confusing at first.

**Comment by mganss** [comment]
How did you try to map the column? It works for me if I map the column like this:
```c#
[Column("New\nLine")]
public string NewLine { get; set; }
```

**Comment by mganss** [comment]
Closing for now. Feel free to reopen with example code.

**Comment by McPhale** [comment]
Yeah, my bad. Things got crazy over here, I will report back when it slows down.
