### ISSUE TITLE
Instantiating POCOs should ignore fields of interface types

### ISSUE THREAD

**Issue by kbrung** [mganss/ExcelMapper#160]
I have some complicated POCOs that have members defined as interface types. Instantiating these fails of course. Is it possible to skip those?

(Sorry for spamming you with feature requests)

**Comment by mganss** [comment]
Yes, it should be possible to ignore these through the `Ignore` attribute or by calling `Ignore()` (see https://github.com/mganss/ExcelMapper#ignore-properties).

**Comment by kbrung** [comment]
My issue is that I am mapping api classes to Excel. These classes are both autogenerated and out of my control. I can't change them or decorate then.

One of the classes has a IList<>, which ExcelMapper is trying to instantiate. I think the best is just to ignore any members typed with an interface.

**Comment by mganss** [comment]
You can also ignore properties by [using method calls](https://github.com/mganss/ExcelMapper#map-through-method-calls), no need to change the class definition.

But generally speaking you're right. Another possible approach would be to allow the user to configure the creation of types (à la dependency injection).

**Comment by mganss** [comment]
I've added custom object factories. Your scenario (ignore interface properties) works out of the box, but now you can also control the creation of objects like so:

https://github.com/mganss/ExcelMapper/blob/86ddaa624c653d13264907fc8a9f502fb504f85d/ExcelMapper.Tests/Tests.cs#L2453-L2515
