### ISSUE TITLE
Excelmapper did not map all columns?

### ISSUE THREAD

**Issue by kevinvenclovas** [mganss/ExcelMapper#164]
Hi,

how can i fix this problem? The mapper works fine but they skip some values from my excel.

My code:
` var excelPriceItemObjects = new ExcelMapper(filename) { MinRowNumber = 2, }.Fetch<ExcelItemObject>().ToList();`

This is what i get after mapping. Missing more then 80% of the values from the excel

![image](https://user-images.githubusercontent.com/7681603/148029333-bff50fdc-c355-4d8f-981b-964cecb4262c.png)

My Excel:

![image](https://user-images.githubusercontent.com/7681603/148029176-f7bc6e0a-0f8f-451f-93d5-4a46984ded15.png)

My Object
```
public class ExcelItemObject
    {
        [Column(1)]
        public string ArticleNr { get; set; }
        [Column(2)]
        public string ArticleName { get; set; }

        [Column(3)]
        public decimal QTY_VE0 { get; set; }
        [Column(4)]
        public decimal QTY_VE1 { get; set; }
        [Column(5)]
        public decimal QTY_VE2 { get; set; }
        [Column(6)]
        public decimal QTY_VE3 { get; set; }
        [Column(7)]
        public decimal QTY_VE4 { get; set; }

        [Column(8)]
        public decimal PRICE_VE0 { get; set; }
        [Column(9)]
        public decimal PRICE_VE1 { get; set; }
        [Column(10)]
        public decimal PRICE_VE2 { get; set; }
        [Column(11)]
        public decimal PRICE_VE3 { get; set; }
        [Column(12)]
        public decimal PRICE_VE4 { get; set; }

        [Column(13)]
        public int Roundingnumbers { get; set; }

        [Column(14)]
        public decimal EAN_VE0 { get; set; }
        [Column(15)]
        public decimal EAN_VE1 { get; set; }
        [Column(16)]
        public decimal EAN_VE2 { get; set; }
        [Column(17)]
        public decimal EAN_VE3 { get; set; }
        [Column(18)]
        public decimal EAN_VE4 { get; set; }

        [Column(19)]
        public int PricelistId { get; set; }
    }
```

**Comment by kevinvenclovas** [comment]
HI, fixed this issue by adding for each variable a custom mapping without the attribute 'Column' in my ExcelItemObject :

_excel.AddMapping<ExcelItemObject>(14, p => p.EAN_VE0)
            .SetPropertyUsing(v =>
            {
                if ((v as string) == "NULL") return "";
                return v.ToString();
            });

**Comment by mganss** [comment]
The original mapping using attributes looks fine to me but you need to specify `HeaderRow = false` when mapping to column indexes.
