### ISSUE TITLE
Map to rowindex even though mapped cell is null

### ISSUE THREAD

**Issue by vinzlee97** [mganss/ExcelMapper#165]
Hi, first of all, thank you for the awesome framework, appreciated the effort

I tried to reproduce the steps to map row index referenced in this comment: https://github.com/mganss/ExcelMapper/issues/148#issuecomment-929058573

But in my case, I need to map the row index even though the column I mapped to manually has empty cells (null).

Here's my sample model:
```cs
class ExcelModel
{
    [Column("Name")]
    public string Name { get; set; }
    public string Description { get; set; }
    public int RowNumber { get; set; }
}
```

Here's how I map the row number:
```cs
var excel = new ExcelMapper(openDialog.FileName);

excel.AddMapping<ExcelModel>("Description", p => p.Description)
    .SetPropertyUsing<ExcelModel>((p, v, c) =>
    {
        p.RowNumber = c.RowIndex;
        return v;
    });
    
var excelModels = excel.Fetch<ExcelModel>();
```

And here's the sample excel screenshot:
![image](https://user-images.githubusercontent.com/28251913/148498095-d85e7e1b-f85c-49f6-b12d-cd2641422518.png)

The second item will show row number as 0, as I expect it to be 2. Is there any workaround? Any help would be much appreciated.

**Comment by mganss** [comment]
Try setting `SkipBlankRows = true`. This will make sure the func gets called even if the cell is blank.

**Comment by vinzlee97** [comment]
Thanks for the suggestion. Unfortunately, the row number is still not mapped

Here is the updated setup:
```cs
var excel = new ExcelMapper(openDialog.FileName)
{
    SkipBlankRows = true
};

excel.AddMapping<ExcelModel>("Description", p => p.Description)
    .SetPropertyUsing<ExcelModel>((p, v, c) =>
    {
        p.RowNumber = c.RowIndex;
        return v;
    });
    
var excelModels = excel.Fetch<ExcelModel>();
```

![image](https://user-images.githubusercontent.com/28251913/148755627-926be2c1-f168-4a02-a9a5-3140055e9e3d.png)

**Comment by mganss** [comment]
Sorry, I meant `SkipBlankRows = false`, i.e. do not skip blank cells 😳

**Comment by vinzlee97** [comment]
Oopsie, `SkipBlankRows = false` on the other hand works 😅 
I get it that when there's empty cell with formatting on (e.g. bordered), the mapping will keep moving on until it arrives a cell with no formatting at all, is it not? Just curious about it

**Comment by vinzlee97** [comment]
For what I see, when `SkipBlankRows = false` , the mapping continues even though there exists rows with all cells are empty values (and the rows are bordered), as seen in the sample excel:

![image](https://user-images.githubusercontent.com/28251913/148768439-800df92c-7bd9-43e0-a2db-505997b6d509.png)

![image](https://user-images.githubusercontent.com/28251913/148767846-1ea9b794-f8d5-4db9-8e02-5763b2815dd8.png)

Is it intended to be the case? 🤔

**Comment by mganss** [comment]
Yes, that's intended (regardless of the formatting). If `SkipBlankRows` is false, it *does not* skip the blank rows, i.e. it generates objects for the blank rows, too.

**Comment by vinzlee97** [comment]
I see, good to know then.

Thanks, closing for now.

**Comment by DanielWake** [comment]
Just to add on to this as I have been stuck for a while, despite following the instructions above.

Setting HeaderRow to false when initialising an ExcelMapper will stop the mapping of row numbers from working.

`var mapper = new ExcelMapper(workbook) { HeaderRow = true, SkipBlankRows = false };`

**Comment by mganss** [comment]
@DanielWake Can you provide an example that shows the issue?
