### ISSUE TITLE
Map Nested List

### ISSUE THREAD

**Issue by coooooool** [mganss/ExcelMapper#170]
Hey,
Im New Here,
I wanna Map Excel File to Json result

``
 public class ApiDDSRequest
    {

        public List<Unit> units { get; set; }
        public string communicationToken { get; set; }
        public string subscriptionToken { get; set; }
    }
public class Unit
    {
        public string unitNumber { get; set; }
        public List<BreakingPoint> breakingPoints { get; set; }
        public List<Comment> comments { get; set; }
        public List<Product> products { get; set; }
        public List<Hazardous> hazardouses { get; set; }
        public CommodityInformation commodityInformation { get; set; }
        public Vessel vessel { get; set; }
        public LabelTracking labelTracking { get; set; }
        public BlockingUnit blockingUnit { get; set; }
        public Flag flag { get; set; }
    }
..........

How can i do that please
this my Excel Structure:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/w-zariat/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/w-zariat/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

units | companyCode | agencyCode | unitNumber | statusCode | shipper | code | name | countryCode | zipCode | adress1 | adress2 | adress3 | secondName | languageCode | faxNumber | phoneNumber | prefixPhoneNumber | prefixFaxNumber | email | contactName | cityCode | shortName | isAssembly | timeZone | recipient | code | name | countryCode | zipCode | adress1 | adress2 | adress3 | secondName | languageCode | faxNumber | phoneNumber | prefixPhoneNumber | prefixFaxNumber | email | contactName | cityCode | shortName | flagAssembly | timeZone | finalRecipient | unitReference | customerReference | orderNumber | customerUnitNumber | returnUnitNumber | serialShippingContainerCode | referenceFields | code | value | complementaryDatas | date | departureDate | availabilityDate | loadingDate | latestUploadDate | deliveryDate | appointmentDate | deliveryAppointmentDate | customerRequiredDate | isValidationAvailabilityDate | charge | quantity | grossWeight | volume | linearMeter | surface | taxableWeight | netWeight | length | width | height | directionCode | carrierOrTransport | transportModeCode | transportModeType | carrierCode | schemeCode | currencyCode | saleCurrencyCode | equipmentCode | instruction | isSightedInstruction | unitInformation | incotermCode | movementCode | priorityCode | loadingDockCode | unloadingDockCode | loadingTime | packingQuantity | stackabilityLevel | paymentUnitNumber | paymentUnitType | packingType | transportPackingType | transportNumber | registrationNumber | kilometers | costCenter | standardManufactoringLeadTime | breakingPoints | comments | userTryptic | reasonCode | comment1 | comment2 | comment3 | date | readFlag | products | hazardouses | unClassificationCode | hazardousClass | packingGroup | grossWeight | netWeight | volume | comment | commodityInformation | vessel | labelTracking | blockingUnit | flag | communicationToken | subscriptionToken
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | IB | IB01 | 80000247 |   |   | 10000010 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 10000002 | NON GROUP CUSTOMER 3 | ES | 28004 | 1 PLAZA DEL REY | 28004 MADRID | EN |   |   |   |   |   | NON GROUP CUSTOMER 3 | false |   |   |   |   | 335 |   |   |   |   | 11 | LF |   |   |   | 2022-02-03T23:00:00Z | 2022-02-03T00:00:00Z | 2022-02-03T23:00:00Z |   |   |   |   | 47.428 | 60465.0 |   |   |   | 47.428 |   |   |   |   |   | 30 |   |   |   | EUR |   |   |   | false |   | CIF |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | SAP | COM |   |   |   |   | 0 |   |   | 111 | 0 | 0 | 0.0 | 1.0 | 2.0 | COmment |   |   |   |   | d71ea109-22df-0933-e053-72654b0a03d2 | 20279E29-9FDD-41F7-AF36-42040C84A487
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 12 | 00 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 13 | 01 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

</body>

</html>

**Comment by coooooool** [comment]
@mganss , any Solution for that please?

**Comment by mganss** [comment]
Can there be multiple units in each row?
If so, it won't be possible, but see #134 for alternative solutions.
If there's only a single unit per row (with duplicated values for `communicationToken` and `subscriptionToken`), then I'd recommend introducing an intermediate class and map objects of that class to `ApiDDSRequest` after reading from Excel.

```c#
public class Intermediate
{
    public Unit units { get; set; }
    public string communicationToken { get; set; }
    public string subscriptionToken { get; set; }
}

// ...
var intermediates = excelMapper.Fetch<Intermediate>();
var requests = intermediates.GroupBy(i => i.communicationToken + i.subscriptionToken)
    .Select(g => new ApiDDSRequest { communicationToken = g.First().communicationToken, 
        subscriptionToken = g.First().subscriptionToken, 
        units = g.Select(i => i.unit).ToList() }).ToList();
```

**Comment by coooooool** [comment]
unfortunately, there are multiple Units.
I will try the alternative Solution #134
