### ISSUE TITLE
read values from a cells reference from another sheet

### ISSUE THREAD

**Issue by leejeffr** [mganss/ExcelMapper#172]
I have a sheet with inline values for some columns and an cell range reference in other columns. The cell range formula looks like this:
=Master!A1:X2601&""

I am able to read the columns that are defined on the current sheet but not the columns that are defined on the referenced sheet. 

Is it possible to cause value of the cell to evaluate when fetching each row during mapping? 

I notice that part of the problem might be that the header row is part of the cell range reference.

**Comment by leejeffr** [comment]
This does appear to work. turn off header row and map via ordinal or letter. Make sure to use the [FormulaResult] attribute. 

The part that was messing me up was that the column ordinal/index starts at 1 whereas the row index start at 0. I was starting at zero which causes an exception. 

[TestReference.xlsx](https://github.com/mganss/ExcelMapper/files/8101126/TestReference.xlsx)

```
ExcelMapper mapper = new ExcelMapper(filePath) { HeaderRow = false, HeaderRowNumber = 0, MinRowNumber = 2, MaxRowNumber = 20 };
var records = mapper.Fetch<TestReferenceDto>("Sheet1").OfType<TestReferenceDto>().ToList();
....
public class TestReferenceDto
    {
        
        [Column(1)]
        public string Field1
        { get; set; }

        
        [Column(Letter="B")]
        public string Field2
        { get; set; }
                
        [Column(3)]
        public string Field3
        { get; set; }

        
        [FormulaResult]
        [Column(4)]         
        public int Field4
        { get; set; }


        [Column(5)] 
        [FormulaResult]
        public int Field5
        { get; set; }

        [Column(6)]
        [FormulaResult]
        public string Field6
        { get; set; }
        
        [FormulaResult]
        [Column(Letter ="G")]
        public string Field7
        { get; set; }
    }

```

**Comment by mganss** [comment]
OK I've made it clearer in the README that column indexes start at 1. I'm closing this now, feel free to reopen if anything doesn't work.
