### ISSUE TITLE
Custom Mapping for a Type

### ISSUE THREAD

**Issue by Blue101black** [mganss/ExcelMapper#176]
Hi, thanks for the great library.

I was wondering if it's possible to add a custom mapping for specific data types, instead of having to do it for each new class/column.

For example for my use case I want: 

- All columns of type `string` should trim trailing whitespace.
- All columns of type `int?` should return null if the value is not an int instead of ConvertException.

**Comment by mganss** [comment]
Perhaps you can work with the `valueParser` parameter of the `Fetch()` methods. See here for example usage:
https://github.com/mganss/ExcelMapper/blob/eb45777899f25e5a7f6bd27076d8227366867cff/ExcelMapper.Tests/Tests.cs#L262

The `Func` doesn't receive the mapped property's type so it might not be enough for your use case. This could be added, but would be a breaking change.

**Comment by Blue101black** [comment]
Thanks for the quick response 👍 

Looks like you still need to define the columns, so won't quite work for my use case. Thank you.

**Comment by Blue101black** [comment]
Thanks for getting back to me. Just got the chance to look into this again.

You are right. Got it working based on your feedback 👍 

Here is what I did:

```csharp
public class ExcelImporter : IExcelImporter
{
    private ExcelMapper _excelMapper;

    public ExcelImporter()
    {
        _excelMapper = new ExcelMapper();
    }

    public async Task<IEnumerable<T>> FetchAsync<T>(Stream stream)
    {
        object ValueConverter(string colname, object val)
        {
            var properties = typeof(T).GetProperties();
            var property = properties.FirstOrDefault(p => p.Name == colname);

            if (val is string)
            {
                if (property.PropertyType == typeof(int?))
                {
                    return null;
                }

                var value = val as string;

                return value.Trim();
            }
            return val;
        }

        return await _excelMapper.FetchAsync<T>(stream, 0, ValueConverter);

    }
}
```
