### ISSUE TITLE
bug : enum type can not be displayed

### ISSUE THREAD

**Issue by nnvbmmm** [mganss/ExcelMapper#179]
in source code : PopulateHeaderRow()

`var noSubTypeColumns = columns.Value.Where(c => **!c.IsSubType** && c.Directions != MappingDirections.ExcelToObject).ToList();`

(enum)
`ColumnInfo.IsSubType` always will be true

**Comment by mganss** [comment]
Thanks for the report. I've added support for mapping enums from strings in 5.2.387.
