### ISSUE TITLE
Column attribute does not seem to work with dashed column names on records

### ISSUE THREAD

**Issue by Polivando** [mganss/ExcelMapper#180]
Hi!

I need to read/write excel file that contains header cells with dash.
Here is my file structure that I try to read:

Action | DashedColumn-1
-- | --
optional | optional
Update | value that should not be null

Here is my model that I try to map this file to:
```
public record TestModel(string Action)
{
	[Column("DashedColumn-1")]
	public string DashedColumn_1 { get; set; }
	}
```
And here is my code to do the mapping:
```var excel = new ExcelMapper();

var models = excel.Fetch<TestModel>("fileLocation", "Export");

var result = models.Select(m => m.DashedColumn_1).Distinct().ToList();
Assert.That(!result.Contains(null));
```

The problem here is that `DashedColumn_1` is null, while `Action`
 is mapped properly.

I've tried `NormalizeUsing<T>`
 to change `-` to `_`, but that changes column name in an actual file, not just "understands" that column with dash should be treated as property with underscore.

What is the correct way to set up mapping of columns that contain dash in their names?

**Comment by mganss** [comment]
I can't repro. Can you attach an example Excel file to this issue?

**Comment by Polivando** [comment]
[test.xlsx](https://github.com/mganss/ExcelMapper/files/8513166/test.xlsx)
[UnitTest1.txt](https://github.com/mganss/ExcelMapper/files/8513173/UnitTest1.txt)

Here are the excel file and txt with code that I use (model that I'm parsing to + the test itself)

**Comment by mganss** [comment]
This was a known restriction up until now (see https://github.com/mganss/ExcelMapper/issues/102#issuecomment-776694562). I've added support for this use case in 5.2.388.
