### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by MPadini** [mganss/ExcelMapper#183]
Hi, i have implemented this library in a test project. I need to import an excel file with 4k records (or more) but the memory usage increases a lot. do you have any idea about this issue?

An image of the diagnostic tool:
https://photos.app.goo.gl/vG49XFip3pAWyeYRA

Thanks

**Comment by mganss** [comment]
Although I don't think there is a memory leak here, your code keeps the `ExcelMapper` object alive longer than necessary because the `Fetch()` method lazily yields the individual objects of the returned `IEnumerable`. Also, you can call `FetchAsync` using the stream of `IFormFile`. Perhaps try this:

```c#
using var stream = file.OpenReadStream();
var excel = await new ExcelMapper().FetchAsync<BaseExcelFormat>(stream);
return Ok(excel.ToList());
```

**Comment by MPadini** [comment]
Thanks for your answer.
I've tried your solution but I continue with the same problem.

**Comment by mganss** [comment]
The `ExcelMapper` object doesn't need to be disposed (only objects of classes that implement `IDisposable` do). It's at the garbage collector's discretion when it frees memory. It manages its own pool of memory so even though there might be no actual memory leak the GC will still keep memory from unreachable objects allocated so it can use this memory for new managed objects. It's not uncommon to see processes balloon up to several hundred MB quickly although the amount of actual memory used by the application at any point is far lower. Only if there is memory pressure will the GC actually free memory back to the OS.

I won't rule out the possibility of an actual memory leak (either within ExcelMapper or its dependencies like NPOI) but this would need to investigated further. Perhaps you can start here: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak
