### ISSUE TITLE
Column with numeric header value

### ISSUE THREAD

**Issue by butskristof** [mganss/ExcelMapper#190]
Hi, 

In a file I have to import from, there's a column with a header value that is a number. 

Whatever I try to define the column, the results are always null. I've tried assigning the column to the index and letter, and tried a dynamic map. With the dynamic map, it doesn't appear in the returned key value collection. 
Is this a bug, or is there a way I can still point ExcelMapper to the right column? 

I've attached a minimal example to reproduce this behaviour. 

Thanks in advance!
Kristof 

[ExcelMapperNumericHeader.zip](https://github.com/mganss/ExcelMapper/files/8676933/ExcelMapperNumericHeader.zip)

**Comment by mganss** [comment]
Thanks for reporting this. Numeric cells in the header row were unsupported up until now, they should work now (from version 5.2.403).

**Comment by butskristof** [comment]
Thanks for the quick follow-up and resolution!
