### ISSUE TITLE
Use Virtual/Override properties to override column name

### ISSUE THREAD

**Issue by jake8787** [mganss/ExcelMapper#192]
Hi!

I'm trying to use override for properties but it doesn't take it's attributes. Is it supported?

```
public class BaseClass
{
        [Column("Text base")]
        public virtual string Text { get; set; }
}

public class ClildClass : BaseClass
{
        [Column("Text new")]
        public override string Text { get; set; }
}

public class Build
{
        public BaseClass BuildNew()
        {
                return new ClildClass(); 
        }
}

```
In the end I want to see 'Text new' but keep getting 'Text base'

**Comment by jake8787** [comment]
> Fixed in 5.2.404.

Awesome :) 
Enjoying your library! 

Somehow managed to find a workaround though
```
mapper => mapper.Ignore<BaseClass>(x => x.Text),
mapper => mapper.AddMapping<BaseClass>("Text new", x => x.Text)
```

**Comment by jake8787** [comment]
@mganss 

I'm getting both somehow

```
        public class BaseClass
        {
            [Column("Text base")] public virtual string Text { get; set; }
        }

        public class ChildClass : BaseClass
        {
            [Column("Text new")] public override string Text { get; set; }
        }

        public static void WriteToExcel()
        {
            var obj = new List<ChildClass> { new ChildClass() }; 

            var file = new FileInfo(@"D:\file.xlsx");
            WriteToExcel_(obj, file, "sheet").Wait();
        }

        public static async Task WriteToExcel_<T>(IEnumerable<T> objects, FileInfo file, string sheetName)
        {
            try
            {
                var excel = new ExcelMapper();
                await excel.SaveAsync(file.FullName, objects, sheetName);
            }
            catch (Exception ex)
            {
                throw new ExcelMapperConvertException($"Error when writing objects of {typeof(T).FullName} to file {file.FullName}: {ex}");
            }
        }
```

![image](https://user-images.githubusercontent.com/74557823/169402633-a5ec4e35-a667-41dc-968b-7bd6ed1654fe.png)

**Comment by mganss** [comment]
We do want to support multiple mappings so I'm currently unsure how to modify the existing behavior. What's your use case? Are there other derived classes that do not have mappings? Or do you also have base class objects that you want to serialize?

**Comment by jake8787** [comment]
I see that it's not a simple thing considering all possible use cases here.

For me it started from the scenario in which an application forced me to support two versions of the excel file in case column names change. Having one version on Production and another version in development on other environments.
Say having a file based on BaseClass (and all the properties + Text property) on Production and another file based on ChildClass (and all the properties + overridden Text property) on Test environment. 
One method builds the collection and another method takes it and creates a file.

Could it be some additional method that tells the mapper which type defines the column names instead of taking it from the collection definition?

**Comment by mganss** [comment]
Perhaps you could use an additional derived class that defines the mapping for the first case and not define a mapping on the base class at all.

```c#
public class BaseClass
{
    public virtual string Text { get; set; }
}

public class ChildClassA : BaseClass
{
    [Column("Text base")] public override string Text { get; set; }
}

public class ChildClassB : BaseClass
{
    [Column("Text new")] public override string Text { get; set; }
}
```

Another option that comes to mind is to add a property (say, `Inherit`) to `ColumnAttribute` that defines whether the mapping is inherited in derived classes.

**Comment by jake8787** [comment]
I thought about first option too, but it requires creating one unnecessary class.
I like the second option though. It's clear and simple but it requires additional check on your side to make sure that it is indeed a deriver class.

**Comment by mganss** [comment]
IMHO the design creating an additional class is cleaner from an object-oriented POV (you could even make the base class abstract).

I've added the `Inherit` property in 5.2.405. Your original code would now become:

```c#
public class BaseClass
{
    [Column("Text base", Inherit = false)]
    public virtual string Text { get; set; }
}

public class ChildClass : BaseClass
{
    [Column("Text new")]
    public override string Text { get; set; }
}
```
