### ISSUE TITLE
Ganss.Excel.Exceptions.ExcelMapperConvertException: 

### ISSUE THREAD

**Issue by rishabh1275** [mganss/ExcelMapper#193]
I am facing this exception when trying to get DateTime property from excel spreadsheet.

Ganss.Excel.Exceptions.ExcelMapperConvertException: 'Unable to convert "30/04/2022" from [L:1]:[C:8] to System.DateTime.'

Inner Exception : FormatException: String '30/04/2022' was not recognized as a valid DateTime.

**Comment by mganss** [comment]
This probably occurs because the cell is not formatted as a date. You'll have to use custom mapping. For example:

```c#
excel.AddMapping<Product>("Date", p => p.Date)
    .SetPropertyUsing(v => DateTime.ParseExact((string)v, "dd/MM/yyyy", null));
```

**Comment by mganss** [comment]
The snippet was just an example. You need to adapt it to your specific use case:

```c#
string file = @"C:\Users\Rishabh.Gupta\Desktop\MgmtAppSampleData1.xlsx";
var excel = new ExcelMapper(file);
excel.AddMapping<Opportunities>("CreatedDate", p => p.CreatedDate)
    .SetPropertyUsing(v => DateTime.ParseExact((string)v, "dd/MM/yyyy", null));
var opportunities = excel.Fetch<Opportunities>();
```

**Comment by rishabh1275** [comment]
Thank you so much Michael.
I really appreciate your prompt response.
I am new to C# and you really pulled me out of a big issue.
Thanks again.

**Comment by rishabh1275** [comment]
Hi Michael,
Hope you are doing good.
I am doing the above task but the resulted date is 1 day prior to the date I am giving as input.
How should I tackle this problem?

**Comment by mganss** [comment]
I have a feeling this has got to do with local vs UTC time. Is your local time ahead of UTC by more than around 5 and a half hours?
By default, `DateTime.Parse()` parses a string that doesn't have timezone information as local time.

**Comment by rishabh1275** [comment]
Yes, it is 5 hours and 30 minutes ahead of Coordinated Universal Time.

**Comment by mganss** [comment]
Then everything's fine. The time in the second screenshot is UTC and exactly midnight of the following day in your local time.

**Comment by rishabh1275** [comment]
Yup, and this got me to my desired result ".ToLocalTime()". Thanks so much Michael.
![image](https://user-images.githubusercontent.com/55344761/180924714-00958f30-ca29-4ff4-831c-2eccff865f2c.png)

**Comment by rishabh1275** [comment]
Yup, and this got me to my desired result ".ToLocalTime()". 
Thanks so much Michael.
![image](https://user-images.githubusercontent.com/55344761/180924932-ad6b07ba-a1d5-4f52-bc21-ff0b687501d3.png)
