### ISSUE TITLE
About Dependency Injection

### ISSUE THREAD

**Issue by MrTanXin** [mganss/ExcelMapper#198]
Hi @mganss 
Is it possible to make ExcelMapper support Dependency Injection

**Comment by mganss** [comment]
I'm sure it's possible and I'm open to changes in this area. How would you envision support for DI?

**Comment by MrTanXin** [comment]
I have no idea yet
But I have some trouble with I use ExcelMapper

In my Project, everyone has different permissions. so I need to make lots of ExportModels for different permission.

I hope to use DI with Transient LifeTime so that I can use only one ExcelModel and ignore some properties to control different permissions.

I am not good at using English, so if there is something that is not clear, you can communicate with me again.

**Comment by MrTanXin** [comment]
There is no obstacle, but now it will make development inconvenient because of the need to create a lot of models for different permissions

for example I having some data need to export
| Id | Name | Age | Height | Weight |
| :--- | :--- | :---- | :-- |:-- |
| 1 | Tom | 18 | 170 | 150 |
| 2 | Kevin | 19 | 170 | 140 |
| 3 | Max | 20 | 170 | 130 |
| 4 | Jam | 21 | 170 | 160 |

I need to create a Model

``` CSharp
    public class Person
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }

        public int Height { get; set; }

        public int Weight { get; set; }
    }
```

But not anyone Can Read All Data

Role A: this role only can Export Id and Name so I need to create a new Model
``` CSharp
    class PersonForRoleA
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
```

Role B: this role Cannot Export Age so I need to Create a Model for Role B 
Role C: this role Cannot Export Height and Weight so I need to Create a Model for Role C 
……

This make my project has lots of Models

=========================================================================

I Hope Can Use DI with Transient LifeTime such as ↓↓↓↓
``` CSharp
  var mapper = new ExcelMapper();
  mapper.Ignore(XXX);
  mapper.SaveAsync(XXX);
```
Can solve this problem

**Comment by mganss** [comment]
I'm not sure I understand your use case 100% but I think you can achieve what you want by creating a factory class/method for each role that creates a custom mapper for that role while maintaining a single model class that is being mapped to.

You need to be aware, though, that by default the mappings are shared across instances of `ExcelMapper` through a static `TypeMapperFactory` object (see #199).

```c#
internal class RoleAMapperFactory
{
    TypeMapperFactory TypeMapperFactory { get; } = new();

    public RoleAMapperFactory()
    {
        var excel = new ExcelMapper { TypeMapperFactory = TypeMapperFactory };
        excel.Ignore<Person>(p => p.Age);
        excel.Ignore<Person>(p => p.Height);
        excel.Ignore<Person>(p => p.Weight);
    }

    public ExcelMapper Create() => new() { TypeMapperFactory = TypeMapperFactory };
}
```

Same for all other roles. Then in your DI create singleton objects of `RoleAMapperFactory` etc. and use those to create transient `ExcelMapper` objects through `Create()`.

**Comment by MrTanXin** [comment]
You are right. TypeMapperFactory Can solve my problem. 
Thanks a lot. I will use this to refactor my project
