### ISSUE TITLE
Fetch the content of a specific cell

### ISSUE THREAD

**Issue by sraedler** [mganss/ExcelMapper#201]
Is it possible to map the content of a specific cell to all fetched objects?

**Comment by mganss** [comment]
Can you elaborate and possibly share an example Excel file?

**Comment by sraedler** [comment]
Imagine I want to have a model consisting of an identifier (the value in B4) and values defined by the heading of a column. Consequently, the model consists of the following values: identifier, characteristic, actual, ...
The identifier and the characteristic are together unique for a model.
However, the identifier is the same for all models. In particular, I define the measured part in the sample.

Below you will find an example file:

[sample.xls](https://github.com/mganss/ExcelMapper/files/9250287/sample.xls)

I hope you can follow my idea...

**Comment by mganss** [comment]
I think I understand. I'm afraid that's impossible currently. Perhaps you can read the file twice, first reading the identifier, then map all individual models and set the identifier property of all model objects to the value you have read in the first pass.

**Comment by sraedler** [comment]
ok, too bad...
do you plan to implement something like that?

**Comment by mganss** [comment]
No, I believe this feature is too specific. But I'm open to PRs 😉
