### ISSUE TITLE
Multiple tabs

### ISSUE THREAD

**Issue by aclimarin** [mganss/ExcelMapper#203]
How to deal with xlsx files with multiple tabs? Is there a way to map a specific tab?

**Comment by McPhale** [comment]
You can specify the name of the sheet:

  ```cs
var records = new ExcelMapper().Fetch("filename", "sheetname");
  ```

**Comment by aclimarin** [comment]
Thank you!

**Comment by mganss** [comment]
Alternatively you can also specify the sheet index.
