### ISSUE TITLE
Suggestions on use SkipBlankRows incorrectly

### ISSUE THREAD

**Issue by andywu188** [mganss/ExcelMapper#206]
In the following code, when any cell is empty, it will be skipped.
https://github.com/mganss/ExcelMapper/blob/fe5f7aaa03992e2f8960ecc7846589fddb67294b/ExcelMapper/ExcelMapper.cs#L509

However, SkipBlankRows should be defined as row records. Skip when all cells are empty.

SkipBlankRows is not SkipBlankCells.

this is SkipBlankRows:
![image](https://user-images.githubusercontent.com/31318039/184476853-a986798b-2d54-44e9-a63c-93265ec04615.png)

this is SkipBlankCells:
![image](https://user-images.githubusercontent.com/31318039/184476862-d38e36a3-89c8-4290-952a-aeab2258ea64.png)

It is suggested to amend as follows:
`if (cell != null && (!SkipBlankRows || row.Cells.Any(c => !IsCellBlank(c))))`

**Comment by andywu188** [comment]
Only when all the cells in the row are blank can the processing be skipped.
When it is a dynamic type, when the cell value is blank, it cannot be ignored.
Otherwise, the length of the List<dynamic> properties in the list may be inconsistent. In the List<Entity>, the number of property members of the Entity is the same.

For example, when using List<dynamic> to read:
`
["__indexes__", < ["Name", 0], ["Number", 2], ["Price", 3], ["Offer", 4], ["OfferEnd", 5], ["Value", 6], ["1+2", 7] >]
  ["__indexes__", < ["Name", 0], ["Number", 2], ["Price", 3], ["Offer", 4], ["OfferEnd", 5], ["Value", 6] >]`

ValueParser processing of blank values is also possible. For example, you can convert a blank value of DateTime type to 1970-01-01.
It is also possible to convert a blank value of type bool to none.

` var productsFetched = new ExcelMapper(file) { SkipBlankRows = false }.Fetch(0, (colnum, value) =>
            {
                if(value is string && value.ToString().Length == 0)
                {
                    switch (colnum)
                    {
                        case "Offer":
                            return "NONE";
                        case "OfferEnd":
                            return new DateTime(1970, 1, 1);
                    }
                }
                return value;
            }).ToList();`

**Comment by mganss** [comment]
Thanks for the thorough investigation. Could you provide a PR to fix this?
