### ISSUE TITLE
Using Fetch method in parallel with the same type often throws NullReferenceException (TypeMapperFactory)

### ISSUE THREAD

**Issue by eFse7en** [mganss/ExcelMapper#208]
Using ExcelMapper.Fetch method in parallel for 5 different sheetNames as the same type often throws below error

**Error:**
```
  Message: 
System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
Dictionary`2.set_Item(TKey key, TValue value)
TypeMapperFactory.Create(Type type)
ExcelMapper.Fetch(ISheet sheet, Type type, Func`3 valueParser)+MoveNext()
Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
List`1.ctor(IEnumerable`1 collection)
Enumerable.ToList[TSource](IEnumerable`1 source)
DataModelExcel.GetEntityFields(String sheetName) line 135
```

**My code triggering the issue:**
```csharp
private static List<DataModelRow> GetEntityFields(string sheetName)
{
    return new ExcelMapper(@"Resources\Model\" + DATA_MODEL_FILE_NAME) { TrackObjects = false }
           .Fetch<DataModelRow>(sheetName)
           .ToList();
}
```

TrackObjects = false or true doesn't seem to change anything.

**Potential solution:**

I'm suspecting that the issue is connected with [ExcelMapper/TypeMapperFactory.cs](https://github.com/mganss/ExcelMapper/blob/master/ExcelMapper/TypeMapperFactory.cs#L21). ConcurrentDictionary with GetOrAdd would probably solve the issue.

**Workaround:**
As a workaround I've added following code to create the type before either Fetch is called:
```csharp
static DataModelExcel()
{
    new Ganss.Excel.TypeMapperFactory().Create(typeof(DataModelRow));
    Thread.Sleep(100);
}
````

**Comment by mganss** [comment]
Thanks. Was able to repro in a unit test and your suggested fix works 👍🏻
