### ISSUE TITLE
How to format dates?

### ISSUE THREAD

**Issue by glmworkemail** [mganss/ExcelMapper#210]
When using the DataFormatAttribute, your docs say, "default format for DateTime cells is 0x16 ("m/d/yy h:mm")".

But I need "yyyy-MM-dd"

I looked in the "builtin formats, but don't  see the format i need.

How can i do this?

**Comment by mganss** [comment]
You should be able to specify the format in the `DataFormat` attribute, i.e. `[DataFormat("yyyy-MM-dd")]`

**Comment by glmworkemail** [comment]
Well that was embarrassingly simple.  Thank you.
