### ISSUE TITLE
Parameter count Mismatch

### ISSUE THREAD

**Issue by rishabh1275** [mganss/ExcelMapper#217]
I am facing this inner exception of Parameter count Mismatch.
and main is "Unable to convert "ManagementAppDbHandler.Notes" from [L:1]:[C:-1] to ManagementAppDbHandler.Notes".

**Comment by mganss** [comment]
Can you attach a demo Excel file and the class definition you're trying to map to?

**Comment by rishabh1275** [comment]
Hi Michael,
I am having these Column names in excel and I am transferring the same after modelling to MongoDB.
![image](https://user-images.githubusercontent.com/55344761/191446903-1dfe91c6-1664-44e3-b859-f4d3bc93c782.png)
but the case is that I don't have Version inside my excel file and I created a version Interface like this
![image](https://user-images.githubusercontent.com/55344761/191447129-6bc17739-9fb8-4ca0-84c2-bbf6386b8b6c.png)
and implemented the interface in model class like this
![image](https://user-images.githubusercontent.com/55344761/191447323-3bf11f64-b8a0-413c-99c7-b689934a0bdc.png)
So I want to do the same for Notes I have to store a Notes Object which will be having list of notes in it and by following the same process I had created Notes class like this with Notes properties
![image](https://user-images.githubusercontent.com/55344761/191447757-79e075f7-406e-42c2-9cb6-6c63d6bb4369.png)
 and Interface same as version like this
![image](https://user-images.githubusercontent.com/55344761/191447902-74866edb-5efe-445e-91b0-11248082c7db.png)
and I am trying to implement the same in my model class but it is getting accessed while iterating through properties.
![image](https://user-images.githubusercontent.com/55344761/191448270-6d0e051f-5ea1-4500-897b-85aef0e21184.png)

**Comment by mganss** [comment]
I'm not sure I understand this yet. Perhaps you just need to decorate `Version` etc with `[Ignore]`?

**Comment by rishabh1275** [comment]
*Resolved*
Hi Michael,
You're amazing I didn't knew about that [Ignore] part.
Thanks so much.
