### ISSUE TITLE
Localized Header Row value while Saving the excel

### ISSUE THREAD

**Issue by prabhpahul** [mganss/ExcelMapper#223]
Hi, is there a way to localize the header while saving the excel through a stream?  I have list of objects of a specific type, currently the Header row is mapped to the name of the field, trying to do AddMapping but it's not working.

Thank you again for your time and consideration.

**Comment by prabhpahul** [comment]
`using (MemoryStream mem = new MemoryStream())
            {
                SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.
                    Create(mem, SpreadsheetDocumentType.Workbook);
                WorkbookPart workbookpart = spreadsheetDocument.AddWorkbookPart();

                workbookpart.Workbook = new Workbook();

                Sheets sheets = spreadsheetDocument.WorkbookPart.Workbook.
                                                        AppendChild<Sheets>(new Sheets());

                var em = new ExcelMapper();
                
                em.AddMapping<FtagExcelHeader>(StaticLocalizerHelper.GetLocalizedMessage("Tag No"), x => x.tagNo);
                em.AddMapping<FtagExcelHeader>(StaticLocalizerHelper.GetLocalizedMessage("Title"), x => x.title);
                await em.SaveAsync(mem, list);
                return mem.ToArray();
            }`

**Comment by mganss** [comment]
You'll have to first call `Ignore()` to remove the automatic mapping:

```c#
em.Ignore<FtagExcelHeader>(x => x.tagNo);
em.Ignore<FtagExcelHeader>(x => x.title);
```

IIRC the reason for this behavior is because you can have multiple mappings for a single property.
