### ISSUE TITLE
Return string.empty when the type is string

### ISSUE THREAD

**Issue by KrzysztofPajak** [mganss/ExcelMapper#228]
Hi,
I would like to suggest, when we want to pass an empty string currently we get a null value. When property type is string and value is empty we should get value string.empty not null.
https://github.com/mganss/ExcelMapper/blob/e4f0a70d1141ff50265d72844b901c7df5446f3b/ExcelMapper/ColumnInfo.cs#L307

Thanks

**Comment by mganss** [comment]
Thanks for the suggestion. Fixed in 5.2.472.

**Comment by KrzysztofPajak** [comment]
@mganss Thanks!
