### ISSUE TITLE
An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module.

### ISSUE THREAD

**Issue by asafgo** [mganss/ExcelMapper#230]
HI,

I am receiving an error "An unhandled exception of type 'System.ExecutionEngineException' occurred in Unknown Module." when trying to import attached Excel file.
[Test1.xlsx](https://github.com/mganss/ExcelMapper/files/10231317/Test1.xlsx)

**Comment by mganss** [comment]
What does your class declaration look like? Works fine for me using this:

```c#
public class Customer
{
    [Column(Letter = "A")]
    public string Phone { get; set; }
}

var mapper = new ExcelMapper("Test1.xlsx") { HeaderRow = false };
var customers = mapper.Fetch<Customer>().ToList();
```

**Comment by asafgo** [comment]
I am using ASP.NET Core MVC with .NET Core 7.

My Class:

```
public sealed class ExcelImportOption1
    {
        [Column(1)]
        public string MobileNumbers { get; set; }
    }
```

Code for read from Excel file:

```
IEnumerable<ExcelImportOption1> mobilenumbers;
mobilenumbers = new ExcelMapper(file) { HeaderRow = false }.Fetch<ExcelImportOption1>();
```

If I am using this Excel file it is working without any problem.
[Test4.xlsx](https://github.com/mganss/ExcelMapper/files/10244076/Test4.xlsx)

I suspect something at Test1.xlsx that all numbers a formulated ?

**Comment by mganss** [comment]
I can't repro. `ExecutionEngineException` may point to all kinds of causes not necessarily related to ExcelMapper. Have you explored the remedies described here? https://stackoverflow.com/questions/49197624/weird-error-system-executionengineexception-occurred-in-mscorlib-dll

**Comment by asafgo** [comment]
I have attached ExcelMapper project to my solution in order to debug and sometimes it works and sometimes fail with the error ExecutionEngineException on Create and it happens only with Test1.xlsx as others works fine.
