### ISSUE TITLE
ExcelMapper in memory instead of saving

### ISSUE THREAD

**Issue by SvenQCompany** [mganss/ExcelMapper#232]
Hello, 

Is it possible to keep the created excel in memory instead of saving it? 
I am looking at this package as it seems to be the only in which you can pass in a list of objects and it will save it in a good manner to excel. Whereas in others you have to do all row and column selections by hand.

I however need to return the created excel file from my API and would rather not have to write it first to the server to then remove it again.

Thanks in advance!
Sven

**Comment by mganss** [comment]
Sure, use one of the overloads of `Save()` that take a `Stream` object to save to, e.g. a `MemoryStream`.
