### ISSUE TITLE
DateOnly type exports to excel with all its components (Year, Month, Day...)

### ISSUE THREAD

**Issue by ruboarm** [mganss/ExcelMapper#233]
I have a model with DateOnly property. Even when I add DataFormatAttribute, while exporting to excel I get all the components of DateOnly struct.
The database is PosgreSQL, and the property of type "date".

As well there are 4 columns with DateOnly? type (All of them can have null values, so they are all marked as nullable), but I get only one date object data filled with all its components.

How to export it to a single cell in a Date format for excel like it is filled in the database with "dd/mm/yyyy" format?

**Database data**
![image](https://user-images.githubusercontent.com/94679525/210562932-d3739b67-76e1-409b-ab73-3f7accebdb58.png)

**Model property**
![image](https://user-images.githubusercontent.com/94679525/210562622-0132d393-654b-42bb-b0c8-89d64edddfa6.png)

**Exported data**
![image](https://user-images.githubusercontent.com/94679525/210562479-cf689bdc-f649-4839-8d7c-a8acddc7dd0f.png)

**Comment by mganss** [comment]
There is no support in ExcelMapper for `DateOnly` (yet). ExcelMapper treats `DateOnly` as a nested type and serializes all of its properties. You should be able to work around this by using [custom mapping](https://github.com/mganss/ExcelMapper#custom-mapping).

**Comment by ruboarm** [comment]
I've created custom mappings for all the 4 properties having DateOnly type. Now they are all exported into excel as expected.
Thanks for the help 👍
I hope that the DateOnly support will be added soon.
