### ISSUE TITLE
unable to convert system string

### ISSUE THREAD

**Issue by krangaraj** [mganss/ExcelMapper#237]
HI there:
im' using your library to read the excel file as observable class, i'm getting an error message:   Message=Unable to convert "(10x8)x2 H Rectangular" from [L:1]:[C:1] to System.String. 

This is the code to read the excel file: thanks for your help. 

```
string excelfilepath = fileDialog.FileName;
var excel = new ExcelMapper(excelfilepath) { TrackObjects = true };

excel.AddMapping<Product>("Mainproduct", p => p.Mainproduct) ;
excel.AddMapping<Product>("Name", p => p.Name);
excel.AddMapping<Product>("Price", p => p.Price) ;
excel.AddMapping<Product>("Visible", p => p.Visible) ;
excel.AddMapping<Product>("NameIcon", p => p.NameIcon) ;

Items = new ObservableCollection<Product>(excel.Fetch<Product>().ToList());
foreach (var st in Items)
{
    View = CollectionViewSource.GetDefaultView(st);
    View.Filter = Filter;
    View.Refresh();

}
```

**Comment by mganss** [comment]
Can you attach an example Excel file to this issue? Thanks.

**Comment by krangaraj** [comment]
Hi there: please find attached the file. [](url)
[Price_202301251120.xlsx](https://github.com/mganss/ExcelMapper/files/10500321/Price_202301251120.xlsx)

**Comment by mganss** [comment]
I can't repro. Works fine for me. FWIW if the property names match the column headers you don't need the calls to `AddMapping`. Also, `TrackObjects` is true by default.
What does your class definition look like?

**Comment by krangaraj** [comment]
Hi there: great? 
What’s wrong with the above code that I used  to read the excel?  
could you please paste your code?
Here is the class:

public class Product
{
    public Product(XElement xe3) => this.xe4 = xe3;
    private XElement xe4;
    public string Mainproduct 
    { 
        //get => xe4.Name.LocalName;  
        get
        {
            
            return xe4.Name.LocalName;
        }
        
    }
    public string Name 
    {
        get => xe4.Attribute("Name").Value; 
        
    }
    public string Price
    {
        get
        {
            XElement xe5 = xe4.Descendants("ProductPrice").FirstOrDefault();
            if (xe5 == null) return string.Empty;
            return xe5.Attribute("Price").Value;
        }
        set
        {
            XElement xe5 = xe4.Descendants("ProductPrice").FirstOrDefault();
            if (xe5 != null) xe5.Attribute("Price").Value = value;
        }
    }
    public string Visible
    {
        get
        {
            XElement xe5 = xe4.Descendants("ProductVisibility").FirstOrDefault();
            if (xe5 == null) return string.Empty;
            return xe5.Attribute("Visible").Value;
        }
        set
        {
            XElement xe5 = xe4.Descendants("ProductVisibility").FirstOrDefault();
            if (xe5 != null) xe5.Attribute("Visible").Value = value;
        }
    }
    public string NameIcon
    {
        get
        {
            XAttribute xe5 = xe4.Attribute("DefaultIconName");
            return (xe5 == null) ? string.Empty : xe5.Value;
        }
        set
        {
            XAttribute xe5 = xe4.Attribute("DefaultIconName");
            if (xe5 == null) xe4.Add(new XAttribute("DefaultIconName", value));
            else xe5.Value = value;
        }
    }

    public override string ToString()
    {
        return "Product Category:" + Mainproduct + ", " + " " + "Product Size:" + Name + ", " + " " + "Visibility:" + Visible + ", " + " " + "Icon:" + NameIcon;
    }

}

**Comment by mganss** [comment]
The properties `Mainproduct` and `Name` don't have a setter. Also, I'm not sure if not having a default constructor will work. Perhaps you'll need to use the [object factory](https://github.com/mganss/ExcelMapper#object-factories) feature.

**Comment by krangaraj** [comment]
Ok thanks I’ll add setter to those properties then I’ll try.

**Comment by krangaraj** [comment]
Hi there:
after rewrtiting the class, i can read the excel file using your library, since its a view model, i'm not able to load it to the View, could you please help me? thanks 

```
var excel = new ExcelMapper(excelfilepath) { TrackObjects = true };
excel.AddMapping<Products>("Mainproduct", p => p.Mainproduct);
excel.AddMapping<Products>("Name", p => p.Name);
excel.AddMapping<Products>("Price", p => p.Price);
excel.AddMapping<Products>("Visible", p => p.Visible);
excel.AddMapping<Products>("NameIcon", p => p.NameIcon);

Items = new ObservableCollection<Products>(excel.Fetch<Products>() );
foreach (var st in Items)
{
    View = CollectionViewSource.GetDefaultView(st);
    View.Filter = Filter;
    View.Refresh();

}
```
**view collection get, set:**

```
 private ICollectionView cvs;
    public ICollectionView View
    {

        get
        {
            
            return cvs;
        }
        set
        {
            cvs = value;
            OnPropertyChanged("View");
        }
    }
```
**class products:**
```
  public class Products
    {

        string mainproduct;
        string name;
        string price;
        string visible;
        string nameicon;

        public string Mainproduct
        {
            get { return mainproduct; }
            set { mainproduct = value; }
        }
        public string Name
        {
            get { return name; }
            set { name = value; }
        }
        public string Price
        {
            get { return price; }
            set { price = value; }
        }
        public string Visible
        {
            get { return visible; }
            set { visible = value; }
        }
        public string NameIcon
        {
            get { return nameicon; }
            set { nameicon = value; }
        }
    }
```
`error message:`

![WhatsApp Image 2023-01-26 at 10 57 33 AM](https://user-images.githubusercontent.com/6481990/214807739-005bc4a7-87f3-4107-80c6-4bf3ae58948f.jpeg)

**Comment by mganss** [comment]
Glad you got it to work 👍🏻
