### ISSUE TITLE
Export to excel from data table

### ISSUE THREAD

**Issue by krangaraj** [mganss/ExcelMapper#239]
Hi There:
This is not an issue but i dont know where to raise/ask.

Using your library, is it possible to export the DataTable DataSet to excel .xlsx? thank so much

**Comment by mganss** [comment]
Currently there is no support for mapping to/from DataTables.

**Comment by krangaraj** [comment]
ok thanks so much for your reply. Have a good day!

**Comment by tonyqus** [comment]
NPOI will provide native support for this. ISheet will be able to be converted to DataTable after merging https://github.com/nissl-lab/npoi/pull/1705. 

If you have suggestions, please comment in https://github.com/nissl-lab/npoi/pull/1705
