### ISSUE TITLE
how to wrap text

### ISSUE THREAD

**Issue by MrTanXin** [mganss/ExcelMapper#244]
Hi,I have a string like this "111\n222\n333"

I want to have 3 rows of data in one cell, like this
![image](https://user-images.githubusercontent.com/26486470/221527272-09085bd9-5576-4f7d-bdb5-d9514e34e2f7.png)

but I try to export list by ExcelMapper ,I got this string "111222333" 
It doesn't display properly until I click on the cell

I don't know if there is a better way to solve this problem
Thanks a lot

**Comment by mganss** [comment]
You'll have to set the `WRAP_TEXT` property of the cell's style. There's currently no simple way to do this. You'll have to something like this:

```c#
var excel = new ExcelMapper();
excel.AddMapping<NewlineProduct>("Name", p => p.Name)
    .SetCellUsing((c, o) =>
    {
        CellUtil.SetCellStyleProperty(c, CellUtil.WRAP_TEXT, true);
        c.SetCellValue(o as string);
    });
```
