### ISSUE TITLE
ParseEnum wil not throw exception when unknown string value is provided

### ISSUE THREAD

**Issue by RichardPoes** [mganss/ExcelMapper#249]
Say we have an enum as follows
```csharp
public enum Awesomeness {
    MediumAwesome,
    SuperAwesome
}
```
and the POCO
```csharp
public class People {
    public string Name { get; set; }
    public Awesomeness Awesomeness { get; set; }
}
```
Now I let this be my table
| Name    | Awesomeness       |
|---------|-------------------|
| Richard | SuperDuperAwesome |

Then no exception is thrown and this is parsed as:
```csharp
{
    Name = "Richard",
    Awesomeness = Awesomeness.MediumAwesome
}
```

Which is not so awesome. I would want to fix this, but I do need to know how you would like to change this.

**Comment by mganss** [comment]
+1 for the test case naming 🤣 

`System.Text.Json` throws an exception so I guess we should mimic this by throwing the `ExcelMapperConvertException` that exists already.
