### ISSUE TITLE
fetch wrong value in other column issue

### ISSUE THREAD

**Issue by samecity** [mganss/ExcelMapper#251]
HI, when i fetch 4,5 column have null value, but i get tables II ,the null value has been covered by column 2,3.
<table>
<tr>
<td>RowNumber </td>
<td>Name</td>
<td>Amount </td>
<td>Name </td>
<td>Amount</td>
</tr>
<tr>
<td>1</td>
<td>A</td>
<td>1541670 </td>
<td>C </td>
<td>466600</td>
</tr>
<tr>
<td>2</td>
<td>A1 </td>
<td>2981180</td>
<td>C1 </td>
<td>466600</td>
</tr>
<tr>
<td>3</td>
<td>A2 </td>
<td>0</td>
<td></td>
<td></td>
</tr>
<tr>
<td>4</td>
<td>A2-1</td>
<td>0</td>
<td></td>
<td></td>
</tr>
<tr>
<td>4</td>
<td>A2-2</td>
<td>78859.02 </td>
<td>C4</td>
<td>143582</td>
</tr>
</table>
<table >
<tr>
<td>RowNumber </td>
<td>Name</td>
<td>Amount </td>
</tr>
<tr>
<td>1</td>
<td>C </td>
<td>466600</td>
</tr>
<tr>
<td>2</td>
<td>C1 </td>
<td>466600</td>
</tr>
<tr>
<td>3</td>
<td>A2 </td>
<td>0</td>
</tr>
<tr>
<td>4</td>
<td>A2-1</td>
<td>0</td>
</tr>
<tr>
<td>4</td>
<td>C4</td>
<td>143582</td>
</tr>
</table>

```c#
class Test {
    public int RowNumber {  get; set; } 
    public string Name {  get; set; } 
    public double Amount {  get; set; } 
}
ExcelMapper Mapper= new ExcelMapper(filePath)
{
    SkipBlankRows = false,
    HeaderRow = true,
    HeaderRowNumber = 8,
    MinRowNumber = 9,
};
t = typeof(Test);
Mapper.AddMapping(t, 1, "RowNumber");
Mapper.AddMapping(t, 4, "Name");
Mapper.AddMapping(t, 5, "Amount");
Mapper.Fetch<Test>();
```

**Comment by mganss** [comment]
This use case isn't covered by the default functionality but I think you can work around this by using custom mapping:

```c#
mapper.AddMapping<Test>("Name", c => c.Name).SetPropertyUsing((o, v, c) =>  c.ColumnIndex != 3 ? null : v);
mapper.AddMapping<Test>("Amount", c => c.Amount).SetPropertyUsing((o, v, c) => c.ColumnIndex != 4 ? null : v);
```
