### ISSUE TITLE
Dynamic Columns

### ISSUE THREAD

**Issue by nisar-ahmad** [mganss/ExcelMapper#253]
I have an Excel file that defines group membership as shown in the screenshot. The number of groups/columns is dynamic and determined at runtime. Can I read them into an object like this?
````csharp
public record Data (string Name, string Description, string[] Groups);
````
![image](https://user-images.githubusercontent.com/2451350/235531642-4f71cb34-198b-4739-b69c-d4bf36610e31.png)

**Comment by mganss** [comment]
It's not supported out of the box but you can use custom mapping to get it to work. Some changes were necessary:

- Uses a class instead of a record
- Had to introduce a dummy property (`Group`)
- You need to know the maximum number of group columns (10 in the example below)

Hope this can work for your use case.

```c#
class Data
{
    public string Name { get; set; }
    public string Group { get; set; }
    [Ignore]
    public List<string> Groups { get; set; } = new();
}

var excel = new ExcelMapper("path/to/file.xlsx");

for (var i = 1; i < 10; i++)
{
    excel.AddMapping(typeof(Data), $"Group {i}", "Group").SetPropertyUsing<Data>((o, v) =>
    {
        o.Groups.Add(v.ToString());
        return null;
    });
}

var ds = excel.Fetch<Data>().ToList();
```

**Comment by nisar-ahmad** [comment]
Thanks for the response. I'll give it a try. I solved it by using dynamic mapping for now. Can I get the total number of columns from the mapper instead of hardcoding 10?

**Comment by mganss** [comment]
You cannot get the number of column from the ExcelMapper API but you can through NPOI. So you might want to load your Excel file into an NPOI Workbook first, get the number of columns, then pass the Workbook into ExcelMapper.
