### ISSUE TITLE
How can addMapping read index when headerRow is true

### ISSUE THREAD

**Issue by Ahmad-F123** [mganss/ExcelMapper#265]
I try with headerRow false, working fine but when headerRow is true, data will get empty

**Comment by Ahmad-F123** [comment]
I try with headerRow false, working fine but when headerRow is true, data will get empty

**Comment by mganss** [comment]
Can you provide example code that shows the issue?

**Comment by Ahmad-F123** [comment]
var mapData = getMapData(); // return obj with indexvalue for Name, Title and Author also return HeaderRow 
var excel = new ExcelMapper(@"..\..\..\products.xlsx");
    excel.HeaderRow = mapData.HeaderRow; // issue happen if headerRow is true
    excel.AddMapping<Book>(mapData.Name, p => p.Name);
    excel.AddMapping<Book>(mapData.Title, p => p.Title);
    excel.AddMapping<Book>(mapData.Author, p => p.Author);

    var books = excel.Fetch<Book>().ToList();

**Comment by mganss** [comment]
Can you show the class declarations for `Book` and the class of the `mapData` object?

**Comment by Ahmad-F123** [comment]
public class Book
{
    public string Name { get; set; }
    public string Title { get; set; }
    public string Author { get; set; }
    
}

public class mapData
{
    public int Name { get; set; }
    public int Title { get; set; }
    public int Author { get; set; }
    public bool HeaderRow { get; set; }

}

**Comment by mganss** [comment]
If you're working with column indexes (not column names), then `HeaderRow` should always be false. If you still want to skip the first row when reading data, set `MinRowNumber` to 1.
