### ISSUE TITLE
Release a new version based on NPOI 2.6.1

### ISSUE THREAD

**Issue by tonyqus** [mganss/ExcelMapper#269]
NPOI 2.6.1 is released. Can we have a new release for ExcelMapper?

Btw, why is there no support for .NET Standard 2.1 in ExcelMapper?

![image](https://github.com/mganss/ExcelMapper/assets/772561/6fe54357-840f-40be-8169-764f9119424b)

**Comment by mganss** [comment]
Sure. I've just released 5.2.528.

AFAIK the .NET Standard targets represent minimum requirements, i.e. a library that supports netstandard2.0 will also run on all platforms that support netstandard2.1.
