### ISSUE TITLE
Pull string value not formula

### ISSUE THREAD

**Issue by Reddevildragg** [mganss/ExcelMapper#27]
Is there a way to pull a string raw value instead of the formula?

Got some fields with formatting (mm:ss) which excel counts as time and can not adjust to text without losing the formatting, then this is used to calculate other times. This is use to show length in minutes and seconds, but gets pulled in as a full dateTime and causing some issues. The field is marked as a string but wanting to just bring in the raw value in the field as written without the formula

Thanks

**Comment by mganss** [comment]
So the cell is a DateTime but it's not getting mapped correctly? Have you tried experimenting with [data formats](https://github.com/mganss/ExcelMapper#use-specific-data-formats)? If all else fails, you can try [custom mapping](https://github.com/mganss/ExcelMapper#custom-mapping).

**Comment by Reddevildragg** [comment]
It maps most the dateTime fine, but there are a few minus values (basically showing an reduction in time) and these do not map correctly due to not being able to have a negative datetime (in excel i have had to change the formate to 1904 in order for it to show correctly).

My current solution is using the custom mapping, but with 20+ cells has taken a bit of time to write the mapper, its up and running now at least, but yeah was more thinking is there an easier way going forward.

Hop that kinda makes sense

**Comment by mganss** [comment]
Currently I don't think there is an easier way. Perhaps in the future we can add another attribute to select between actual formula and formula result output for string properties.

**Comment by Reddevildragg** [comment]
No worries, just wanted to make sure I had not overlooked something pretty obvious and overcomplicated my problem.

Thanks for the help, would think may be a useful feature in a future release.

**Comment by mattaze** [comment]
What would the custom mapping look like to get the destination property which is String to have the value instead of the function?
The SetCellValue does not appear to get triggered, SetPropertyUsing is triggered, but at that point is still just the formula.

```
public class SalesForecast
{
    [Column("Patt No")]
    public string Productnumber { get; set; }
}

var excelMapper = new ExcelMapper(workbook);
excelMapper.AddMapping<SalesForecast>("Segment", sf => sf.Segment)
    .SetCellUsing((c, o) => {
        if (o == null) {
            c.SetCellValue("NULL");
        } else {
            o = c.StringCellValue;
            c.SetCellValue((String)o);
        }
    })
    .SetPropertyUsing(v => {
        if ((v as string) == "NULL") {
            return null;
        }
        return Convert.ChangeType(v, typeof(String), System.Globalization.CultureInfo.InvariantCulture);
    });
```

**Comment by mganss** [comment]
Added in #30
