### ISSUE TITLE
DateOnly Mapping

### ISSUE THREAD

**Issue by nisar-ahmad** [mganss/ExcelMapper#273]
DateOnly fields are incorrectly being parsed as DateOnly.MinValue. We have to use DateTime and do conversions. Is there a workaround or custom mapping that we can use?

**Comment by mganss** [comment]
DateOnly is now supported (from 5.2.535). Wasn't straightforward to implement, as netstandard2.0 and net462 don't have DateOnly so had to use reflection.

**Comment by nisar-ahmad** [comment]
Thanks for the prompt enhancement. Really appreciate it. Your library is extensively used in our product and makes our lives so much easier!
