### ISSUE TITLE
Wrong cell values with SkipBlankCells=true

### ISSUE THREAD

**Issue by rmolino** [mganss/ExcelMapper#275]
Hello,
I have a xlsx-file which contains cells in the following format. Each cell can be empty:
Wert: decimal (value or empty - currently retrieved as string)
Soll: char ('S' or empty)
Haben: char ('H' or empty)
Both char colums are never set at the same time. So we always have: 'S' + '', '' + 'H' or '' + ''

Nevertheless I was getting the both column values set: 'S' + 'H'
![image](https://github.com/mganss/ExcelMapper/assets/77544001/efbb9d8c-399f-43df-b969-6c7861e0ff70)

I could fix it by setting "SkipBlankCells = false". Nevertheless I should never get wrong results, regardless of the configuration.

```c#
using (var stream = new MemoryStream(dateiInhalt))
{
    var excelMapper = new ExcelMapper(stream)
    {
        HeaderRowNumber = 1,
        MinRowNumber = 2,
        SkipBlankCells = false, // seems to fix the issue
        HeaderRow = true
    };
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Wert);
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Soll);
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Haben);
    var wertDaten = excelMapper.Fetch<WertDaten>().ToArray();
    // ...
}

public class WertDaten
{
    public string Wert { get; set; }
    public string Soll { get; set; }
    public string Haben { get; set; }
}
```

Best regards,
Raul

**Comment by mganss** [comment]
Can you attach an example Excel file?

**Comment by rmolino** [comment]
Sample file attached.
![image](https://github.com/mganss/ExcelMapper/assets/77544001/a3c58297-d6bc-49cb-86ca-320e4b9a91e7)
Row: "DDDDD" Columns: Jan/2020 S H
[Test.xlsx](https://github.com/mganss/ExcelMapper/files/12523290/Test.xlsx)

**Comment by mganss** [comment]
You need to set `HeaderRow` to false. The header row is used to map from header names to property names which in your case does not apply since you're mapping via column index.

**Comment by rmolino** [comment]
ok, thx for the fast support. I will check it tomorrow.
Nevertheless, the description is misleading, because the file contains a header row, regardless how the mapping is performed. Or does a documentation exist that I have not found till now?

![image](https://github.com/mganss/ExcelMapper/assets/77544001/ecc164f3-6d35-4858-95be-61b12445bf28)

**Comment by rmolino** [comment]
I just tested it with HeaderRow=false und still have the wrong result like reported.
`
var excelMapper = new ExcelMapper(stream)
{
    HeaderRow = false,
    HeaderRowNumber = kopfzeilePosition,
    MinRowNumber = ersteDatenzeilePosition
};

`

**Comment by mganss** [comment]
Strange. Can you check if it works if you don't set `HeaderRowNumber`?

**Comment by rmolino** [comment]
Still the same result
![image](https://github.com/mganss/ExcelMapper/assets/77544001/f68db619-d1f0-4277-a480-90f325c0c1e2)

**Comment by mganss** [comment]
I can't repro. This is the code I've tested with:

```c#
class WertDaten
{
    public string Wert { get; set; }
    public string Soll { get; set; }
    public string Haben { get; set; }
}

var dateiInhalt = File.ReadAllBytes("Test.xlsx");
var startSpalte = 2;

using (var stream = new MemoryStream(dateiInhalt))
{
    var excelMapper = new ExcelMapper(stream)
    {
        MinRowNumber = 2,
        HeaderRow = false
    };
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Wert);
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Soll);
    excelMapper.AddMapping<WertDaten>(++startSpalte, s => s.Haben);
    var wertDaten = excelMapper.Fetch<WertDaten>().ToArray();
    // ...
}
```

Note that the column numbers are one-based, so `startSpalte` needs to be initialized to 2 in the code above to read the first block of objects.

**Comment by rmolino** [comment]
some more info: this issue does not occure the first time data of a certain type is fetched. It needs to be at least the second time. It may also be the first time on the second file. Is there some kind of caching?

Here the test code. On the second loop run using the previously attached file I get the following result:
![image](https://github.com/mganss/ExcelMapper/assets/77544001/1ee85bef-dd24-47f8-b388-4e6f2a96fba8)
```
        private void Test(byte[] dateiInhalt)
        {
            List<ExcelMonatsWert> result = new();
            int column = 3;
            for (var cnt = 1; cnt <= 2; cnt++)
            {
                using (var stream = new MemoryStream(dateiInhalt))
                {
                    var excelMapper = new ExcelMapper(stream)
                    {
                        HeaderRow = false,
                        MinRowNumber = 2
                    };
                    excelMapper.AddMapping<ExcelMonatsWert>(column++, s => s.Wert);
                    excelMapper.AddMapping<ExcelMonatsWert>(column++, s => s.Soll);
                    excelMapper.AddMapping<ExcelMonatsWert>(column++, s => s.Haben);
                    var wertDaten = excelMapper.Fetch<ExcelMonatsWert>().ToArray();
                    foreach (var d in wertDaten)
                    {
                        Console.WriteLine($"{d.Haben} - {d.Soll}");
                    }
                }
            }
        }

```

```
        public class ExcelMonatsWert
        {
            public string Kontonummer { get; set; }
            public Monat Monat { get; set; }
            public string Wert { get; set; }
            public string Soll { get; set; }
            public string Haben { get; set; }
        }

```

**Comment by mganss** [comment]
Yes, that's the problem here. The default `TypeMapperFactory` is static, caching `TypeMapper` objects across instances of `ExcelMapper`. The easiest workaround is to pass a new instance of `TypeMapperFactory` whenever you create a new ExcelMapper object:

```c#
var excelMapper = new ExcelMapper(stream)
{
    MinRowNumber = 2,
    HeaderRow = false,
    TypeMapperFactory = new TypeMapperFactory()
};
```

If you're processing many files and performance becomes an issue you might want to cache instances of `ExcelMapper` for each individual value of `startSpalte`.

**Comment by rmolino** [comment]
thanks, this solved my issue. Performance is for my current use-case still good
