### ISSUE TITLE
How to map an image property?

### ISSUE THREAD

**Issue by LJN-hzleaper** [mganss/ExcelMapper#297]
My dto has a image property, for example a WPF BitmapImage property, how to map it to a excel column?
I have tried following code, but it didn't work.

```
ExcelMapper mapper = new();
mapper.AddMapping(typeof(Dto), "Image", nameof(Dto.Image));
mapper.Save("E:/Test.xlsx", GetData(), "Hi");

public class Dto
{
    public BitmapSource Image
    {
        get=> new BitmapImage(new Uri("E:/1.png")); 
        set{}
    } 

    public int Id { get; set; }

    public string? Name { get; set; }
}
```

**Comment by mganss** [comment]
There is no builtin support for images yet. But you can try [custom mapping](https://github.com/mganss/ExcelMapper?tab=readme-ov-file#custom-mapping).
