### ISSUE TITLE
Allow Empty Cells For Decimals

### ISSUE THREAD

**Issue by lucusP320** [mganss/ExcelMapper#3]
Is there a way to ignore empty cells and not add a value? My problem is that if i have a column with a decimal it will add 0 to it or if i have a date column that is empty it will add a date.  I know i can use a null able value for some items but that wont work for required items in the class. 

My end goal is to allow the user to upload the excel file and then catch issues with the excel upload with data annotations.  So if they accidentally leave a column blank i don't want  a value there.  Then i can use model state validation with data annotations to log the errors and display it back to the user.

**Comment by mganss** [comment]
Can you post an example?

**Comment by lucusP320** [comment]
My issue isn't really with the library.  The library works well.  I am inheriting from a class because the class is huge and has a lot of properties.  In the Parent class the property customerId is not nullable and required for other reasons.  I would like it to be nullable when i use the library to map the excel file to the object.  The reason being is i can then easily just use Model State validation to figure out where the user may have messed up in the excel file.        

Because I have so many properties i don't want to rewrite the class.  I have other classes and places i will use this as well.  I will have about 10-20 properties i need to check on where i can use Max Length as an example.  So doing the Model State validation will give me all the errors.     


I basically want to do something like this where i can set a data annotatoin to allow a null value.  Then maybe in the ExcellMapper look for that attribute and if it exists allow to dump empty or null values in that property.  

```
public class TestChild: Test
{
        [Required]
        [IsNullableForExcel(true)]
        public override int customerId { get; set; }
}

public List<TestChild> GetExcelRecordsTest(Stream stream)
{
        var mappedList = new ExcelMapper(stream).Fetch<TestChild>();
        List<TestChild> failedList = new List<TestChild>();
        List<TestChild> finalList = new List<TestChild>();

        foreach(var result in mappedList )
        {
             var context = new ValidationContext(result, null, null);
            var validationResult = new List<ValidationResult>();

             if (Validator.TryValidateObject(result , context, validationResult , true))
             {
                 finalList.Add(customer);
             }
             else
             {
                  //Will add more to a view model in the future to get well defined errors
                  failedList.Add(customer);
              }
         }
}

```

**Comment by mganss** [comment]
Would it be feasible to use nullable wrapper properties in the child class?

```C#
public class TestChild: Test
{
        private int? _myCustomerId;

        [Required]
        [Column("customerId")]
        public int? MyCustomerId
        {
            get
            {
                return _myCustomerId;
            }

           set
           {
               _myCustomerId = value;
               myCustomerId = value.GetValueOrDefault();
           }
        }
}
```

**Comment by lucusP320** [comment]
Unfortunately there are a lot of properties that are set to non-nullable.  If i change them to allow nulls then there are several functions and other places which I would have to make changes to allow nulls.  I didn't write the main code base just trying to catch some bad data from excel uploads before it makes it to the database.     

The solution i came up with was to set default values for the properties i need to validate against and then created some custom data annotations.  My customer numbers will always be greater than 0 so i just set the value to -1 and then use a custom data annotation [NumericIsNotEmpty] to check this.  I also created one for date and check if the year is 0001 and a few other annotations for property types i need.

After i get the list of objects with the Excel Mapper i can use model state validation to check for bad rows and get all the errors for that row.     

public class TestChild: Test
{
        [Required]
        [NumericIsNotEmpty]
        public override int customerId { get; set; } = -1;
}

I wonder if there is a way to implement something like this into your library?  Either create an override function for Take or modify it to return an object with two lists.  It would return a list for valid rows and a second list with non valid rows.  Maybe in the PropertyInfo there could be a check for [Required] and if any of the properties in that row are required and have an empty value that could be placed in the non valid rows list.  Not sure if this is even possible but would be a nice feature.   


You can close this if you would like.

**Comment by mganss** [comment]
I'm trying to keep the library lean and focused on the mapping aspect so I'd rather not add this feature right now. Thanks for your suggestions, though.
