### ISSUE TITLE
Change Column Title

### ISSUE THREAD

**Issue by BourgisDaniele** [mganss/ExcelMapper#300]
Good morning,
it would be very useful to have the ability to set the title of the columns, only those that have the title different from the property name.
Currently I am forced to clean the list of columns and do AddMapping, otherwise the columns with different title are added at the end.

Thank you,

**Comment by mganss** [comment]
Does that happen if you add `[Column]` attributes?

**Comment by BourgisDaniele** [comment]
Thanks for the answer, but we can't use attributes, because we have different export for the same entity that must have different column titles ..
