### ISSUE TITLE
Issue with Ignore() function

### ISSUE THREAD

**Issue by juliensaunier** [mganss/ExcelMapper#301]
Hi,

I am using ExcelMapper since few weeks now and find it fantastic !!!
However I have faced an issue recently with the Ignore() function.
I am using ExcelMapper in a .Net API. where I have two controllers named Import and Export.
In the Export controller I called the ignore() function for one field because I don't want it in the generated object:

excelMapper.Ignore<ExcelTemplatePC>(obj => obj.Crop);

Everything is fine : my generated excel object does not contain the column.

But we I call the other controller (the import) in which I created another instance of the excelMapper object, the crop field is ignored !

Thank for your help 

Regards

JulienS

Here is the code of my API:

[HttpGet]
public IActionResult Export()
{
    var templateExcelPC = new List<ExcelTemplatePC>();

    var excelMapper = new ExcelMapper() { SkipBlankCells = false, SkipBlankRows = false };
    var pathAndFilename = "exporttemplate2.xlsx";

    excelMapper.Ignore<ExcelTemplatePC>(obj => obj.Crop); // careful : once called it is valid for all other calls including in a different controller
                                                                        // i.e. Ignore() called here in the export causing the field to be ignored in the import !! 

    excelMapper.Save(pathAndFilename, templateExcelPC, "PC");

    return File(new FileStream(pathAndFilename, FileMode.Open), "application/octet-stream", "export.xlsx");
}

[HttpGet]
public IEnumerable<ExcelTemplatePC> Import()
{
    var excelMapper = new ExcelMapper() {};
    var pathAndFilename = "Import.xlsx";

    var result = excelMapper.Fetch<ExcelTemplatePC>(pathAndFilename, "PC");

    return result;  // => here the object does not contain any Crop column while it is in another controller !
}

**Comment by mganss** [comment]
See https://github.com/mganss/ExcelMapper/issues/199#issuecomment-1180615609

**Comment by mganss** [comment]
@juliensaunier Thanks for the kind words! ❤️

**Comment by juliensaunier** [comment]
That's wonderful ! 
Thank you for your fast answer ! 
I tried this solution :
var excel = new ExcelMapper("test.xlsx") { TypeMapperFactory = new TypeMapperFactory() };

And it works like a charm !

This library is so amazing !

Thank you again :)

JulienS
