### ISSUE TITLE
Reading values without format

### ISSUE THREAD

**Issue by xts-velkumars** [mganss/ExcelMapper#306]
@mganss, How do I read the value without format

Below is my issue 

I need to read the IDNO as **"8005065137086"**. But I'm seeing its coming as **"8.00507E+12"**

![image](https://github.com/mganss/ExcelMapper/assets/13570225/ed917e7a-0e8d-4fe3-9692-8a8accf4697d)

![image](https://github.com/mganss/ExcelMapper/assets/13570225/f42e42ef-22cd-44ae-b070-dc208dc173e6)

**Comment by mganss** [comment]
What's the property type you are mapping to?

**Comment by xts-velkumars** [comment]
I have attached the sample excel. I have declared IdNumber as string in my code. 

[Test.xlsx](https://github.com/user-attachments/files/15800290/Test.xlsx)

**Comment by mganss** [comment]
From 5.2.590 there is now support for custom formats that override the format specified in the Excel file. Define your class like so:

```c#
class XYZ
{
     [DataFormat(1)]
     public string IdNo { get; set; }
}
```

Of course you could also just define the property as long.

**Comment by xts-velkumars** [comment]
@mganss, Thanks for your response. 

But still its not coming up what I'm excepting. 

I'm doing anything wrong? 

```
 var rows = new ExcelMapper(file.FullName)
 {
     CreateMissingHeaders = true,
     HeaderRow = true
 }.Fetch<MemberDataViewModel>().ToList();
```

Below is my model and result.

![image](https://github.com/mganss/ExcelMapper/assets/13570225/5918920b-ba5d-4a2f-9f80-635145599e21)

![image](https://github.com/mganss/ExcelMapper/assets/13570225/c8ce8e81-8802-449c-96e2-6acc1053d160)

**Comment by mganss** [comment]
Are you using the latest version (5.2.590)?

**Comment by xts-velkumars** [comment]
@mganss, I'm using version 5.2.588. My project is using .NET Framework 4.61

**Comment by xts-velkumars** [comment]
@mganss, I have updated the ExelMapper to the latest version. Its working like a charm. 

Thank you so much
