### ISSUE TITLE
@mganss, Thanks for your response.

### ISSUE THREAD

**Issue by xts-velkumars** [mganss/ExcelMapper#307]
@mganss, Thanks for your response. 

But still its not coming up what I'm excepting. 

I'm doing anything wrong? 

```
 var rows = new ExcelMapper(file.FullName)
 {
     CreateMissingHeaders = true,
     HeaderRow = true
 }.Fetch<MemberDataViewModel>().ToList();
```

Below is my model and result.

![image](https://github.com/mganss/ExcelMapper/assets/13570225/5918920b-ba5d-4a2f-9f80-635145599e21)

![image](https://github.com/mganss/ExcelMapper/assets/13570225/c8ce8e81-8802-449c-96e2-6acc1053d160)

_Originally posted by @xts-velkumars in https://github.com/mganss/ExcelMapper/issues/306#issuecomment-2165728031_

**Comment by mganss** [comment]
See #306
