### ISSUE TITLE
Can't use object as property type

### ISSUE THREAD

**Issue by asherber** [mganss/ExcelMapper#309]
Given this spreadsheet:

![image](https://github.com/user-attachments/assets/f551ce6b-22bc-4119-bc2f-b1363d01a92e)

And this class:

```csharp
public class Record
{
    public object Name { get; set; }
    public object Age { get; set; }
}
```

I get these results in LinqPad from `new ExcelMapper(file).Fetch<Record>().Dump();`:

![image](https://github.com/user-attachments/assets/eeff1ee1-eea8-49f4-9196-26fc4c59914c)

Is it a known limitation that properties need to be defined with more definite types than `object`? It would be nice if this worked.

**Comment by mganss** [comment]
Fixed in 5.2.592
