### ISSUE TITLE
load error - default XML namespace of the project must be the MSBuild XML namespace

### ISSUE THREAD

**Issue by mkamoski** [mganss/ExcelMapper#37]
...

Dear ExcelMapper Developers, 

Please help.

How can one fix this project load error -- default XML namespace of the project must be the MSBuild XML namespace -- quickly and completely?

Here are the details.

I just downloaded a zip, unzipped it, opened in Visual Studio 2015, and got the following load errors.

(1)

C:\Users\mfk1234\Documents\DevNotes\ExcelMapper-master\ExcelMapper-master\ExcelMapper\ExcelMapper.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\abc1234\Documents\DevNotes\ExcelMapper-master\ExcelMapper-master\ExcelMapper\ExcelMapper.csproj

(2)

C:\Users\abc1234\Documents\DevNotes\ExcelMapper-master\ExcelMapper-master\ExcelMapper.Tests\ExcelMapper.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\abc1234\Documents\DevNotes\ExcelMapper-master\ExcelMapper-master\ExcelMapper.Tests\ExcelMapper.Tests.csproj

Please advise.

Thanks.

-- Mark Kamoski

...

**Comment by mkamoski** [comment]
FYI, it seems to open fine in Visual Studio 2019, so I guess that is the "answer" here?

**Comment by mganss** [comment]
The project uses the new csproj format which is unsupported in VS 2015. It should work in VS 2017, however. Also, you should be able to just copy the source files to an existing project in VS 2015, though I'm not sure it will compile because the project might use a few C# 7 features that are not supported in VS 2015. Can't you use the NuGet package?

**Comment by mkamoski** [comment]
Ok. Great. I just upgraded to visual studio 2019 and it worked perfectly so thank you for that.
