### ISSUE TITLE
Suggestion: throw custom exception type instead of NullReferenceException when sheet doesn't exist

### ISSUE THREAD

**Issue by rgoliveira** [mganss/ExcelMapper#39]
Instead of crashing with a `System.NullReferenceException` when you pass in a sheet name that doesn't exist to `Fetch`, it would be friendlier to detect it and throw a custom exception. I believe `WorkbookFactory` returns `null` when the sheet is not found.
Let me know if this makes sense to you too. I could work on this.

**Comment by mganss** [comment]
I think this is a good case for the [ArgumentOutOfRangeException](https://docs.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception). We can throw that and include the original exception in the `InnerException` property. Would be nice if you could add this.

**Comment by rgoliveira** [comment]
I'm on it. Just one thing: there's no "original exception" to include in the `InnerException`, since I'll detect that the `Workbook` came out `null` from `Workbook.GetSheet`.
