### ISSUE TITLE
Ignoring formula columns in header row in excel sheets

### ISSUE THREAD

**Issue by McPhale** [mganss/ExcelMapper#4]
Hello! 

I've got a spreadsheet that has a formula as its final column (in the header row) that I'm trying to run through my API.  

ExcelMapper works great if I delete that column from the spreadsheet, but throws an exception if I leave it in.  (Cannot get a text value from a numeric formula cell).  I've tried setting the Ignore attribute on my mapping class for the requisite column, but it doesn't seem to help. 

Any tips? I would just remove the column from the spreadsheet but it's sent to my system by another department, so I don't have any control over it.

**Comment by mganss** [comment]
Thanks for reporting this. Fixed in 1.0.18.

**Comment by McPhale** [comment]
Thank you for fixing it! I'll give it a go with the latest version and I'll let you know how it goes.
