### ISSUE TITLE
Test ExcelMapperConvertExceptionTests.EmptyConstructorTest breaks due to localization

### ISSUE THREAD

**Issue by rgoliveira** [mganss/ExcelMapper#41]
The test `ExcelMapperConvertExceptionTests.EmptyConstructorTest` checks if the automatic message from the exception is `Exception of type '{typeof(ExcelMapperConvertException).FullName}' was thrown.`, but my installation localizes the message to my language, so the test breaks... I'd argue that this test doesn't add much in terms of coverage, so it shouldn't exist, since it'd be weird to check for localized messages.

**Comment by mganss** [comment]
True. I've changed the test to simply assert the object is not null so as to keep the coverage for the default constructor 😄
