### ISSUE TITLE
Getting excel header column list without specifying a type

### ISSUE THREAD

**Issue by mahabubulhasan** [mganss/ExcelMapper#42]
My problem scenario is i have various kind of excel that i want to read. Ahead of reading i don't know what type of excel it is. I need to determine the type by reading the header columns. So Is there any way to get the column list without specifying the type for example instead of this
```C#
var excel = new ExcelMapper("products.xlsx").Fetch<Product>()
```

Thanks.

**Comment by mganss** [comment]
No, ExcelMapper is all about mapping to specific types. You could use NPOI directly to sniff the type that your Excel file contains and then pass the `IWorkbook` to ExcelMapper and do a `Fetch` with the type you have identified.
