### ISSUE TITLE
Style just in the header

### ISSUE THREAD

**Issue by cafs3011** [mganss/ExcelMapper#46]
How do you set style just in the header? Like bold word or diferent font size just in header?

**Comment by mganss** [comment]
What's your use case?
You can create an empty Excel file (using Excel), format the header as you wish, then create an ExcelMapper object from this template, fill it with data and save to a new file.

**Comment by cafs3011** [comment]
In fact, I needed that the generated file could already come with the header in bold or with filling in some color. It's possible?

**Comment by mganss** [comment]
Yes. Here's how this works:
- Create an Excel file with just the header, styled as you wish
- Load this file using ExcelMapper
- Fill it with data
- Save

Example code:

```c#
var excel = new ExcelMapper("styledHeader.xlsx");
var products = new List<Product>();
products.Add(...);
excel.Save("products.xlsx", products);
```
