### ISSUE TITLE
Ignore Header/ AutoFit

### ISSUE THREAD

**Issue by abbottmw** [mganss/ExcelMapper#47]
Is there a simple way to not create a header when passing a list of objects?  I just want the data.  Can it go by column index?
Also is there a way to autofit columns in a sheet?

**Comment by mganss** [comment]
Set the `HeaderRow` property to `false`. More on mapping without a header row here: https://github.com/mganss/ExcelMapper#map-to-column-indexes

There's nothing in ExcelMapper to control Excel formatting such as autofitting columns but you can access NPOI's `IWorkbook` interface through the `Workbook` property and work with that.

**Comment by abbottmw** [comment]
The Workbook property is private.   Can I create a new NPOI workbook, and somehow call the AutoFit Property before calling the Save()

IWorkbook workbook = new XSSFWorkbook();
workbook.CreateSheet();
 var mapper = new ExcelMapper(workbook);
....
//auto fit here?
mapper.Save(path, list);

**Comment by mganss** [comment]
Yes, exactly.

**Comment by abbottmw** [comment]
The question I have about it is the Save() method takes the list and saves it, so adding the autofit before  the save is pointless as there is no data in the workbook passed in at that point.

What am I missing?

**Comment by mganss** [comment]
Sorry, you're right. I think currently the only way is to call `Save()`, keep a reference to the workbook, autofit, then save again using `Workbook.Write()`.

**Comment by nsulikowski** [comment]
You can basically save to `Stream.Null` (to throw away the serialization), and keep working on the resulting workbook using native NPOI.
When you are done with your changes you can serialize again using `workbook.Write()`
For example:

```
var workbook = new XSSFWorkbook();
var mapper = new ExcelMapper(workbook);
mapper.Save(stream: Stream.Null, objects: split_rows!, sheetName: "Data");

//more edits using native NPOI                            
ISheet sheet = workbook.GetSheet("Data");
sheet.DisplayGridlines = false;
sheet.CreateFreezePane(0, 1);

using var ms = new MemoryStream();
workbook.Write(ms, leaveOpen: true);
return File(fileContents: ms.ToArray(), contentType: Funcs.XLSX_ContentType, fileDownloadName: "text.xlsx");
```
I think it would be nice to have a version of the Save method that just updates the workbook.

**Comment by mganss** [comment]
@nsulikowski We already have a ton of overloads for `Save()`. A quick way of implementing this would be to introduce a null check before writing to the stream.
