### ISSUE TITLE
Issue mapping class without property attributes

### ISSUE THREAD

**Issue by akordowski** [mganss/ExcelMapper#50]
I'm trying to map a class without property atrributes to load a Excel sheet. Here is my approach:

```
var excel = new ExcelMapper(filePath);
excel.AddMapping<Model>(0, p => p.Property1);
excel.AddMapping<Model>(1, p => p.Property2);
...
var result = excel.Fetch<Model>();
```
and
```
var excel = new ExcelMapper();
excel.AddMapping<Model>(0, p => p.Property1);
excel.AddMapping<Model>(1, p => p.Property2);
...
var result = excel.Fetch<Model>(filePath, 0);
```

In both cases the mapping has no effect, The mapper resolves the properties using the column names in the first row. Tried with a multilanguage excel file with same format but different column names.

Am I doing something wrong? Any help is welcomed!

**Comment by mganss** [comment]
Have you tried `HeaderRow = false`?

**Comment by akordowski** [comment]
I had to set
```
excel.HeaderRow = false;
excel.MinRowNumber = 1;
```
to prevent convert exceptions for the first row.

**Comment by akordowski** [comment]
Ich schreibe weiter auf Deutsch, fällt mir einfacher den Gedanken zu vermitteln.

Für mich ist das ein nicht intuitives Verhalten. Wenn ich das Mapping setze, dann erwarte ich, dass es das Default Verhalten (Mapping über die Column Namen) ignoriert. Ich sehe das als einen Bug.

Desweiteren habe ich noch das Problem, dass Spalten mit Datumwerten als double nicht konvertiert werden. Das double Datum müsste in dem Fall mit `DateTime.FromOADate()` konvertiert werden. Eine Idee wie ich das machen kann? Vielen Dank im voraus!

**Comment by akordowski** [comment]
see #51

**Comment by mganss** [comment]
You're right. Keep in mind, though, that you can mix mapping by column index and name for use cases where you want to save Excel files having a header row with columns in a specific order.

**Comment by akordowski** [comment]
But the problem is that the mixed behavior doesn't work at all, at least for the import. Thats why I run in this issue in the first place.

When I use a excel file with column names in the first row and a I set mapping by index for e.g. 2 columns, the mapping doesn't work. I had to set `excel.HeaderRow = false` to take the mapping effect. And than I also have to set `excel.MinRowNumber = 1` to prevent convert exceptions. But then the mapping by name dosn't work.

The expected behavior would be mapping columns by column name in the first row, the mapping overrides this when set.

Can I some how help you to verify this problem?

**Comment by mganss** [comment]
I have fixed this in 5.0.138 😄

**Comment by akordowski** [comment]
Thank you very much, I will test it!

**Comment by akordowski** [comment]
I can confirm that following code works now for a excel file with a header row
```
var excel = new ExcelMapper(filePath);
excel.AddMapping<Model>(0, p => p.Property1);
excel.AddMapping<Model>(1, p => p.Property2);

var result = excel.Fetch<Model>();
```
but the mapping over the column names (mixed behaviour) doesn't work in this case.

**Comment by mganss** [comment]
Another option would be to prefer mappings by index over mappings by name. 

However, this would potentially result in other (non-intuitive?) situations where a property P is explicitly mapped to, say, column 1 and an Excel table contains a column with header name P that is **not** column 1.

A similar problem already exists where you manually map a property P to a column name N and there exists a different property named N.

Perhaps we should establish rules:
- Index mapping > explicit name mapping > implicit name mapping
- Only one mapping per property

**Comment by akordowski** [comment]
Yes, you are right. I have to think about it. But your idea make sense.
