### ISSUE TITLE
Guids crash on Fetch

### ISSUE THREAD

**Issue by luxdave** [mganss/ExcelMapper#52]
When importing a file with Guidvalues, it crashes on the SetProperty method in TypeMapper.cs.
It throws the following error: Invalid cast from 'System.String' to 'System.Guid'
How it is now: 
```
public void SetProperty(object o, object val)
        {
            object v;
            if (SetProp != null)
                v = SetProp(val);
            else if (IsNullable && (val == null || (val is string s && s.Length == 0)))
                v = null;
            else
                v = Convert.ChangeType(val, PropertyType, CultureInfo.InvariantCulture);
            Property.SetValue(o, v, null);
        }
```

How I fixed it:
```
public void SetProperty(object o, object val)
        {
            object v;
            if (SetProp != null)
                v = SetProp(val);
            else if (IsNullable && (val == null || (val is string s && s.Length == 0)))
                v = null;
            else if (PropertyType == typeof(Guid))
                v = Guid.Parse(val.ToString());
            else
                v = Convert.ChangeType(val, PropertyType, CultureInfo.InvariantCulture);
            Property.SetValue(o, v, null);
        }
```
It still throws an error for invalid Guids this way.

Anyway, Awesome work!

**Comment by mganss** [comment]
You can use custom type mappings using `SetPropertyUsing()` as shown here without the need to modify ExcelMapper: https://github.com/mganss/ExcelMapper#custom-mapping

To prevent exceptions being thrown for invalid values you can use the [`Guid.TryParse()`](https://docs.microsoft.com/en-us/dotnet/api/system.guid.tryparse?view=netframework-4.8) method.
