### ISSUE TITLE
Not gettting all columns 

### ISSUE THREAD

**Issue by alexkbecker** [mganss/ExcelMapper#58]
Hi, How are you?
      First of all this library is amazing.
      But, I have a Excel with sereral Sheets with 27 columns, for some reason not all columns are returning data, I had to comment out the following line: 283 (.Where (c =>! HeaderRow || (c.CellType == CellType.String &&! string.IsNullOrWhiteSpace (c.StringCellValue) ))) from ExcelMapper.cs so that the library could recognize and return all the data in the spreadsheet, it seems that it is ignoring the property, I saw that there is an issue closing reporting something similar, but I'm using the mapping via index and not by name...
[TesteExcelMapper.zip](https://github.com/mganss/ExcelMapper/files/4461947/TesteExcelMapper.zip)

**Comment by mganss** [comment]
If you're not mapping via the header row then you need to set `HeaderRow = false` (even though the sheet may contain a header row which you're not using for mapping columns to properties). In your example the data rows start at index 4 (numbering starts at 0 not 1!) so this seems to work:

```c#
var planilhaRessarcimento = new ExcelMapper(@"Dados\FICHAS_CAT_42.xlsx") 
{ 
    SkipBlankRows = true, 
    TrackObjects = false, 
    MinRowNumber = 4, 
    HeaderRow = false 
};
```

`SkipBlankRows = true` isn't even necessary for the specific example, nor is `TrackObjects = false`.

**Comment by alexkbecker** [comment]
It worked!!!!
Thanks man!!!
