### ISSUE TITLE
Constructor taking Workbook

### ISSUE THREAD

**Issue by 79it** [mganss/ExcelMapper#6]
Hello,

Could you consider adding a constructor to inject the workbook please?

```
    public ExcelMapper(IWorkbook workbook)
    {
        Workbook = workbook;
    }
```
I need to verify column headings exist correctly for multiple sheets and have borrowed some code from ExcelMapper that loads in a workbook to do this.

If it were possible to pass this workbook in the constructor of ExcelMapper it would mean not having to load the Excel file for every sheet I want to fetch - I tried with stream but it closes it after the first read.

Thanks

Chris

**Comment by mganss** [comment]
Sure. Added in 4.0.32.
