### ISSUE TITLE
Any plan for async I/O support?

### ISSUE THREAD

**Issue by lhrbu** [mganss/ExcelMapper#62]
Thanks for your effort, ExcelMapper is so cool and easy to use, and I'm trying to embed it in some asp net core projects where async I/O support is extremely important in such scenarios, so could we expect some async version of Save() and Fetch() methods like: 
`await new ExcelMapper().SaveAsync("products.xlsx", products, "Products");`
`var products = await new ExcelMapper("products.xlsx") { HeaderRow = false }.FetchAsync<Product>();`

**Comment by mganss** [comment]
We're using NPOI under the covers which exposes a synchronous API only. I think the best bet would be to asynchronously read the Excel file into a `MemoryStream` (using [`CopyToAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copytoasync?view=netcore-3.1#System_IO_Stream_CopyToAsync_System_IO_Stream_)?) then continue to process synchronously (CPU bound). You can do this from your code today but I'll add wrapper methods soon.
