### ISSUE TITLE
property of rows other than first row are taking null or default value if first row column property is empty

### ISSUE THREAD

**Issue by raviranjanpandey** [mganss/ExcelMapper#64]
I am a relatively new user to this library and I am getting one issue while importing data from excel. if any column of the first row is empty then other row's data for that column is also setting property value to its default value even if there is data in that row for that column. any help would be appreciated.

**Comment by mganss** [comment]
I can't repro. Can you post a short example along with a demo Excel file?

**Comment by raviranjanpandey** [comment]
For sure. please find the zip attached. 
I have added the mapped data as json and i have taken example from the "b2b" named sheet. for the column index 1 and 3, from sheet index 1, first row has empty data unlike 2nd row but in the mapped json u can see the 2nd item in the list also has null and default date assigned for the properties OrgTradeName, OrgDocDate respectively.
I am mapping the properties using method call.

[excel_import_issue.zip](https://github.com/mganss/ExcelMapper/files/4852785/excel_import_issue.zip)

**Comment by mganss** [comment]
Could you also post the code you're using to read the file? Thanks.

**Comment by raviranjanpandey** [comment]
Sorry, i should have done that before. here is a simplified example of how I am reading data. for this example i am using local file path but in my production, i am using AWS S3 bucket response stream but it really doesn't matter as i am getting error in both cases. one more thing, if I have data in the first row, everything works fine and I get all the data from all the rows correctly.
`               using (Stream file = new FileStream(pathSource, FileMode.Open, FileAccess.Read))
                {
                    var _excel = new ExcelMapper(file)
                    {
                        SkipBlankRows = true,
                        TrackObjects = false,
                        HeaderRow = false,
                        MinRowNumber = 8,
                        MaxRowNumber = int.MaxValue
                    };
                    _excel.AddMapping<Test>(1, p => p.OrgTradeName)
                    .SetPropertyUsing(v =>
                    {
                        if ((v as string) == "NULL") return null;
                        return v.ToString();
                    });
                    _excel.AddMapping<Test>(3, p => p.OrgDocDate);
                    var b2bSheetData = _excel.Fetch<Test>(1).ToList();
                }

    public class Test
    {
        public string OrgTradeName { get; set; }
        public DateTime OrgDocDate { get; set; }
    }
`
Hope it's useful.

**Comment by mganss** [comment]
Fixed in 5.0.166. Thanks.

**Comment by raviranjanpandey** [comment]
Thanks a lot, sir.
