### ISSUE TITLE
Skip row or stop reading after reaching empty cell (not a blank row) or incorrect type

### ISSUE THREAD

**Issue by bandooksage** [mganss/ExcelMapper#65]
Below is an example excel data -
```
+----+-----------------+--------------+
| SL |      Date       |      P1      |
+----+-----------------+--------------+
|    | Opening Balance | USD 10254.66 |
|  1 | 01-07-2020      | 445.25       |
|  2 | 01-07-2020      | 234.80       |
|  3 | 02-07-2020      | 13.00        |
|    | Total           | USD 10947.71 |
+----+-----------------+--------------+
```

Currently my code -
```c#
    public static async IAsyncEnumerable<TReceipt> ReadBankEntry(string file)
    {
        using (FileStream stream = new FileStream(file, FileMode.Open, FileAccess.ReadWrite))
        {
            ExcelMapper mapper = new ExcelMapper() 
            { 
                HeaderRowNumer = 0 // zero is the default
                MinRowNumber = 2 // actual data starts from here (skipping row=1)
                // MaxRowNumber = ? this is dynamic and can change in every excel file.
            };
            // my mapping table here
            foreach (TReceipt bankEntry in await mapper.FetchAsync<TReceipt>(stream, "Sheet1"))
            {
                yield return bankEntry;
            }
        };
    }
```

As you can see in the last row - 
Firstly, is there a way to stop reading or skip rows when the first column is empty but the row isn't?
Second, is there a way to stop reading or skip row when one of the columns does not have a certain type? Or perhaps stop reading or skip row when there is an exception?

**Comment by mganss** [comment]
If the mapping doesn't generate any errors I would probably handle this with a classic `.Where()` (or `.TakeWhile()`). Otherwise you can try and use the [custom mapping methods](https://github.com/mganss/ExcelMapper#custom-mapping) to avoid any errors and then filter.

If you do know the range of rows in advance you can use the [data row range](https://github.com/mganss/ExcelMapper#header-row-and-data-row-range) properties.

**Comment by bandooksage** [comment]
Alright. Used custom mapping to avoid errors, followed by `.Where()` to filter. 

Was hopping there was a way to handle rows with incorrect types to avoid performance drop (over 100000 rows). But this is still the quickest library with a readable code compared to other libraries. Awesome work! Thanks!
