### ISSUE TITLE
How to Save Multiple sheets in single Excel file 

### ISSUE THREAD

**Issue by NaanKaran** [mganss/ExcelMapper#66]
i am trying to save multiple sheets in single excel but there is no option for that. the "Save" extension takes only one IEnumreble .
how to store multiple sheets in single excel 
please do the need full

**Comment by mganss** [comment]
You'll have to make multiple `Save()` calls to the same `ExcelMapper` object.

**Comment by drgrieve** [comment]
I was also stupidly stuck on this as well. Suggest adding a small example to the readme which also takes advantage of Stream.Null.

        var mapper = new ExcelMapper();
        await mapper.SaveAsync(Stream.Null, changes1, "Changes1");
        await mapper.SaveAsync(Stream.Null, changes2, "Changes2");
        await mapper.SaveAsync("changes.xlsx", changes3, "Changes3");
