### ISSUE TITLE
Multiple worksheets

### ISSUE THREAD

**Issue by 2monitors1developer** [mganss/ExcelMapper#68]
Hey, 

is there a way to specify the worksheet to read from, the workbook I need to read from had 4 sheets that can't be deleted?

Cheers.

**Comment by mganss** [comment]
Sure, there are overloads of `Fetch()` that take either a sheet index or name.

**Comment by 2monitors1developer** [comment]
The only thing I didn't check! Thanks for getting back to me 👍

**Comment by kevinvenclovas** [comment]
Hi, is there an option to get the worksheet count? So i can load the sheets dynamically

**Comment by mganss** [comment]
@kevinvenclovas You can easily do this using NPOI, then pass the workbook object to ExcelMapper:

```c#
var workbook = WorkbookFactory.Create("file.xlsx");
var sheets = workbook.NumberOfSheets;
var excelMapper = new ExcelMapper(workbook);
```
