### ISSUE TITLE
Use Json Serializer by Default for Objects 

### ISSUE THREAD

**Issue by ashvinnihalani** [mganss/ExcelMapper#70]
It would be nice to have the library use JSON serializer/deserialize by default rather than having to implement it with a custom handler

**Comment by mganss** [comment]
Should this use `System.Text.Json` (would require net461) or good old `Json.NET`? Or something else entirely? I think we can be opinionated here as the user could always opt for their preferred serializer by implementing custom mapping.

**Comment by ashvinnihalani** [comment]
Probably Json.net since it the recommended way for net core which is the future. I don't know if any deal breakers if we went one way or the other.

**Comment by mganss** [comment]
OK I've used `System.text.Json` and dropped support for net45.
