### ISSUE TITLE
Ignore format of a cell and get plain text 

### ISSUE THREAD

**Issue by davidaso28** [mganss/ExcelMapper#71]
Hi, I would like to know if there is a way to ignore the format of a cell and just take the plain text value.

for example, if I have a cell with value 10-11 of  date format then avoid the 11/10/2020 conversion and just get "10-11" string

Thanks!

**Comment by mganss** [comment]
Good idea, I've added support for this. If you want to change the formatting behavior, you can specify a custom `DataFormatter` object to the `ExcelMapper` object.
