### ISSUE TITLE
Need to map a column multiple times targeting multiple properties

### ISSUE THREAD

**Issue by hguy** [mganss/ExcelMapper#76]
It looks like only the last `mapper.AddMapping<ProductRow>("colname", p => p.propname1).SetPropertyUsing(blabla...)` is used.
It would be useful to allow 
```
mapper.AddMapping<ProductRow>("colname", p => p.propname1).SetPropertyUsing(blabla...)
mapper.AddMapping<ProductRow>("colname", p => p.propname2).SetPropertyUsing(blabla2...)
```

**Comment by mganss** [comment]
Columns currently have a one-to-one mapping to properties. Perhaps you can work around this by using an adapter property whose setter "fans out" to multiple other properties.

I'm open to PRs that change this behavior. If you want to tackle this, go for it, Perhaps [`MultiValueDictionary`](https://github.com/dotnet/corefxlab/blob/b2250a750a25cdbc3b012a34858bc9432e4f5677/src/Microsoft.Experimental.Collections/Microsoft/Collections/Extensions/MultiValueDictionary.cs) from corefxlab can help.
