### ISSUE TITLE
Read/Write style and formatting metadata for each cell

### ISSUE THREAD

**Issue by leejeffr** [mganss/ExcelMapper#79]
I would like to record metadata about each cell. For example, I would like to know that particular value was mapped from a cell with a background color of yellow and text formatting was not strike through.

Likewise I would like to be able to set metadata for each value that I want to write to excel so that I can color a cell and format the text according to my own business logic. 

Is there any support for this?

**Comment by mganss** [comment]
The second use case is already possible now using the [`SetCellUsing()`](https://github.com/mganss/ExcelMapper#custom-mapping) method. I'll add support for the first use case.

**Comment by mganss** [comment]
The second use case is now possible using `SetPropertyUsing()` like in this example:

```c#
excel.AddMapping<GetterSetterProduct>("Name", p => p.RedName)
    .FromExcelOnly()
    .SetPropertyUsing((v, c) =>
    {
        switch (c.CellStyle.FillForegroundColorColor)
        {
            case XSSFColor color when color.ARGBHex == "FFFF0000":
                return v;
            default:
                return null;
        }
    });
```
