### ISSUE TITLE
Mapping with Conversion

### ISSUE THREAD

**Issue by martic** [mganss/ExcelMapper#8]
The Data source I have been working with has changed from CSV to an Excel Table.
I've been using CSVHelper and now wish to use ExcelMapper.
The Excel data I'm importing contains the string "NULL" instead of an empty null value in the null cells.

For CSVHelper you can define a ConvertUsing helper for the Mapper.
How would you suggest I do the same for ExcelMapper?

```
    public class QFDataLoad
    {
        public int EventID { get; set; }
        public string EventType { get; set; }
        public DateTime? Reported { get; set; }
    }

    public sealed class QFDataLoadMap : ClassMap<QFDataLoad>
    {
        public QFDataLoadMap()
        {
            Map(m => m.EventID).ConvertUsing(row => { 
                             return int.Parse(row.GetField("Event ID")); });            
            Map(m => m.EventType).Name("Event Type");
            Map(m => m.Started).ConvertUsing(row => { 
                             return CreateDBDateTime(row.GetField("Reported")); });
        }

        public static DateTime? CreateDBDateTime(string date)
        {
            DateTime result;
            if (DateTime.TryParse(date, out result))
            {
                return result;
            }
            return null;
        }
```

**Comment by martic** [comment]
I have tried to use the custom formats and ignore text (;;;), as I would in excel but this doesnot work.

```
        [Column("Reported"), DataFormat("yyyy-mm-dd hh:mm:ss;;;")]
        public DateTime? Reported { get; set; }
```

**Comment by martic** [comment]
Thanks Michael !
That worked great!

**Comment by felipeleite** [comment]
Following this same idea of Mapping with Conversion, how to map TimeSpan? Like, from excel value "06:40" to TimeSpan propertie?
Thanks.

**Comment by felipeleite** [comment]
> [@felipeleite](https://github.com/felipeleite) Instead of `Convert.ChangeType` in the example above, use `TimeSpan.Parse()`.

Awesome @mganss !!!! Like a charm! Thanks!
