### ISSUE TITLE
Trim Trailing Whitespace on Header Column on Fetch

### ISSUE THREAD

**Issue by DominicArchual** [mganss/ExcelMapper#86]
We are using the ExcelMapper class like so:
```
var excelMapper = new ExcelMapper(payload.FileStream);
excelMapper.SkipBlankRows = true;
ProductMapper.Configure(excelMapper);
Payload.Items = excelMapper.Fetch<ImportModel>().ToList();
```
Our `ImportModel` class looks like this:
```
public class ImportModel
{
	[Name("Color", "COLOR", "Color Name", "ColorName")]
	public string Color { get; set; }
}
```
The problem is, sometimes our Excel documents header columns contain one or more trailing whitespace.  For example, instead of the column header being `Color Name` it will read `Color Name `.

Is there any way to use ExcelMapper to trim whitespace such that the column will still be correctly identified on `Fetch()`?

**Comment by mganss** [comment]
You can now. Use the `NormalizeUsing()` method:

```c#
excelmapper.NormalizeUsing(n => n.Replace(" ", ""));
```

**Comment by DominicArchual** [comment]
> You can now. Use the `NormalizeUsing()` method:
> 
> ```cs
> excelmapper.NormalizeUsing(n => n.Replace(" ", ""));
> ```

Thanks for adding this feature (and so quickly)!
