### ISSUE TITLE
"I" Column Name Problem

### ISSUE THREAD

**Issue by vefaokumus** [mganss/ExcelMapper#87]
Hi. Using Win10 in English but my MS Office is in Turkish. Excel Mapper returns null for the values in "I" column. My first guess is the language or regional settings is the culprit because we have an "İ" letter (I with a dot) in Turkish language. Something is messed up. Any chance to fix this up?

Thanks.

**Comment by mganss** [comment]
Can you provide an example file?

**Comment by vefaokumus** [comment]
Here is an example file attached. Column named "SD1BotNode" in "Analyses" sheet cannot be mapped as a property:

[example01.xlsx](https://github.com/mganss/ExcelMapper/files/5618009/example01.xlsx)

**Comment by mganss** [comment]
This is a [bug in NPOI](https://github.com/nissl-lab/npoi/issues/470) and it seems indeed related to the current culture. Until it is fixed, you can work around this issue by temporarily setting the thread's current culture to en-US for example:

```c#
var culture = System.Threading.Thread.CurrentThread.CurrentCulture;
System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
var excel = new ExcelMapper("example01.xlsx");
System.Threading.Thread.CurrentThread.CurrentCulture = culture;
```

Subsequent calls to the `ExcelMapper` object can be made with the culture set to the original culture, only the constructor call that performs the actual reading of the Excel file using NPOI needs to have the culture set to en-US.

**Comment by vefaokumus** [comment]
I see. Thanks for your great library and work around you provided.
