### ISSUE TITLE
Write to Excel with Column Attribute

### ISSUE THREAD

**Issue by baoduy** [mganss/ExcelMapper#9]
I got an issue when write to excel with Column attribute provided, the data is not writing to excel file.
However it is working fine when remove the attributes.

```csharp
 public class DataItem
    {
        [Ignore]
        public string Bql { get; set; }

        [Ignore]
        public int Id { get; }

        [Column(2)]
        public string OriginalBql { get; }

        [Column(1)]
        public string Title { get; }

        [Column(3)]
        public string TranslatedBql { get; set; }
    }
```

**Comment by mganss** [comment]
Have you specified `HeaderRow = false` when saving? If it still doesn't work please provide a sample Excel file and a code example.

**Comment by baoduy** [comment]
Hi,
Data is there when set `HeaderRow = false`. However I would like to write header down and using Column attribute to re-order the position of the column

Current is `OriginalBql, Title, TranslatedBql` but I would like it is `Title, OriginalBql, TranslatedBql`
How to resolve it?

Thanks

**Comment by mganss** [comment]
Ah ok, I hadn't considered this use case. I've added support for it in 4.0.37.

**Comment by baoduy** [comment]
Thanks for your help and this is a great project which I’m looking for.
