### ISSUE TITLE
Issue with null rows on fetch

### ISSUE THREAD

**Issue by achang-s** [mganss/ExcelMapper#96]
Hello,

I encountered an issue when processing an excel file with null rows (not empty rows) between valid rows. While NPOI knows the proper size of the sheet collection, the loop condition `while (i <= MaxRowNumber && (row = sheet.GetRow(i)) != null)` on line 420 of `Fetch(ISheet sheet, Type type, Func<string, object, object> valueParser = null)` stops looping through the collection if it hits a null row, even if there are more valid rows later on in the sheet.

This is because the index is still looping through the row keys rather than the collection's physical index, [see image for reference, GetRow looks for 19 which is null and never proceeds to 19 the collection since its key is 22](https://user-images.githubusercontent.com/40402335/104530950-ef7e1a00-55c1-11eb-8fcb-2654c75c7104.png).

As a stopgap, in my application I preprocess the file by replacing these null rows with empty rows. Thanks.

**Comment by mganss** [comment]
Can you attach a sample Excel file?

**Comment by achang-s** [comment]
[null_test.xlsx](https://github.com/mganss/ExcelMapper/files/5816145/null_test.xlsx)

Here is a sample file. Row 6 (collection index 5) appears blank but is a null row, [the key that GetRow(i) uses is actually 7](https://user-images.githubusercontent.com/40402335/104630058-264e4180-564f-11eb-94c3-c2af7eee98bc.jpg)

Also, in the process of generating the file, there was another potential issue, I think by deleting rows after the valid data it generated [other entries with a high value](https://user-images.githubusercontent.com/40402335/104630427-978df480-564f-11eb-9d36-431f357c5981.jpg).

**Comment by mganss** [comment]
Thanks. It's fixed in 5.1.253. Regarding the other issue, could you open a new issue and provide steps to repro?

**Comment by achang-s** [comment]
Thanks @mganss. It seems like the other issue I mentioned is no longer a problem now that the iterator is used and only iterates through the actual number of physically present rows. It was only problematic before because my previous preprocess method was also naively using the row key as an index to loop. Not sure why but on LibreOffice Calc deleting rows in a certain way (right click delete on rows existing in the middle of other valid rows, and selecting _Delete entire row_) would set the row number values of the later to rows to over 1,000,000 at least when viewed in NPOI's collection.
