### ISSUE TITLE
Serial vs Parallel, Cast exception

### ISSUE THREAD

**Issue by wahmedswl** [mganss/ExcelMapper#99]
Hi, running same code serially works but running parallel breaks it and throws
```
Unable to cast object of type 'System.String' to type 'System.DateTime'.
```

This throws cast exception
![image](https://user-images.githubusercontent.com/15020561/105626777-e445ac80-5e53-11eb-8618-4b7fb99a2e51.png)

but same with serially works
![image](https://user-images.githubusercontent.com/15020561/105626791-0808f280-5e54-11eb-830a-f9c1baee42f3.png)

Thanks

**Comment by mganss** [comment]
I can't repro. Here's my code:

```c#
var processedExpandos = new List<ExpandoObject>();
var writer = new ExcelMapper { SkipBlankRows = false };
var fn = "parallel.xlsx";
var products = Enumerable.Range(0, 1000).Select(i =>
{
    dynamic p = new ExpandoObject();
    p.Name = $"Name {i}";
    p.Price = i + 0.99m;
    p.Expiration = new DateTime(2000, 1, 1).AddDays(i);
    ((IDictionary<string, object>)p)["__indexes__"] = new Dictionary<string, int>
    {
        ["Name"] = 0,
        ["Price"] = 2,
        ["Expiration"] = 4
    };
    return p;
}).Cast<ExpandoObject>().ToList();

writer.Save(fn, processedExpandos);

Parallel.ForEach(products, p =>
//foreach (var p in ps)
{
    ((IDictionary<string, object>)p).Remove("__indexes__");

    lock (processedExpandos)
    {
        processedExpandos.Add(p);
        writer.Save(fn, processedExpandos);
    }
}
);
```

Can you provide a short example to reproduce the issue?

**Comment by wahmedswl** [comment]
Hi, it seems strange that it should happen in Serial mode as well but it happens when Field is empty. 

![image](https://user-images.githubusercontent.com/15020561/107207146-c6667300-6a21-11eb-96ab-449d53921c82.png)

Also, getting following error in debug mode as well

![image](https://user-images.githubusercontent.com/15020561/107207409-180efd80-6a22-11eb-9847-c0f7817c217c.png)

Thanks

**Comment by mganss** [comment]
Can you provide a sample Excel file?

**Comment by mganss** [comment]
No feedback, closing.
